### ISSUE TITLE
"Could not find module" error when customizing `outputPaths`

### ISSUE THREAD

**Issue by rohmann** [ef4/ember-auto-import#100]
I have this in my `ember-cli-build.js` file:

```
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    ...
    outputPaths: {
      app: {
        css: {
          'app': '/css/app.css',
        },
        js: '/js/app.js'
      },
      vendor: {
        css: '/css/cs-vendor.css',
        js: '/js/vendor.js'
      }
    },
    ...
```

and I'm getting these errors:

```
Uncaught Error: Could not find module `some-module` imported from `app/path-to/i-import-some-module`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at resolveInitializer (index.js:34)
    at registerInitializers (index.js:47)
    at exports.default (index.js:28)
    at Module.callback (app.js:15)
    at Module.exports (loader.js:106)
missingModule @ loader.js:247
findModule @ loader.js:258
Module.findDeps @ loader.js:168
findModule @ loader.js:262
requireModule @ loader.js:24
resolveInitializer @ index.js:34
registerInitializers @ index.js:47
exports.default @ index.js:28
(anonymous) @ app.js:15
Module.exports @ loader.js:106
requireModule @ loader.js:27
(anonymous) @ app-boot.js:3
```

It started working when I moved somethings around to remove the `outputPaths` statement but this is a project requirement due to other integrations.

I was able to get it working by manually updating this line to match my configuration: https://github.com/ef4/ember-auto-import/blob/2d6b55591c4b678adaf177f8024875d8e24248f1/ts/bundle-config.ts#L18

Could I request that `bundle-config.ts` be updated to respect the `outputPaths` parameter of `ember-cli`? Thanks!

**Comment by ef4** [comment]
Yes, good idea, we should definitely do this.

There is probably another wrinkle, which is the location of lazily-loaded chunks. By convention they go in the same directory as vendor.js, so they should also move when the location is customized.
