### ISSUE TITLE
Build error for deleted files

### ISSUE THREAD

**Issue by zeppelin** [ef4/ember-auto-import#11]
Repro steps:

1. Create an empty file: `app/utils/function.js`
1. Didn't import anything from the empty file, so the project compiles successfully
1. Delete `app/utils/function.js`
1. Build error originating from __ember-auto-import__

**Comment by ef4** [comment]
Hi Gabor, thanks for reporting, I can't reproduce this using 1.0.0-alpha.0, please reopen if you are still seeing this.
