### ISSUE TITLE
Package doesn't work with custom output path to site.js and vendor.js specified

### ISSUE THREAD

**Issue by estshy** [ef4/ember-auto-import#117]
Ember cli does allow for configuring custom output path (https://ember-cli.com/user-guide/#configuring-output-paths) but extension seems to be not auto importing external dependencies with following configuration

```
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp({
    outputPaths: {
      app: {
        html: 'index.html',
        css: {
          'app': '/assets/site.css'
        },
        js: '/assets/site.js'
      },
      vendor: {
        css: '/assets/vendor.css',
        js: '/assets/vendor.js'
      }
    }
  });

  //...
  return app.toTree();
};
```

Tested version: 1.2.8

**Comment by ef4** [comment]
This whole area changed in ember-auto-import 2.0, so I'm closing this, if there is still a problem under 2.0 please file a new issue.
