### ISSUE TITLE
custom output filename 

### ISSUE THREAD

**Issue by houfeng0923** [ef4/ember-auto-import#120]
when i want to custom output config (webpack), i found  fingerprint not work well , 
then , i found [this code](https://github.com/ef4/ember-auto-import/blob/master/ts/auto-import.ts#L119), 

in webpack , it support some template config [in output](https://webpack.js.org/configuration/output/)
so , how can we support  custom output filename ?  thank you

**Comment by ef4** [comment]
It would be helpful if you could explain your requirements. What are you trying to achieve?

My goal with this project is to _not_ expose users to a huge number of options. Especially webpack-specific ones.

**Comment by houfeng0923** [comment]
ah, i can see your mind . so it doesn't matter for my  case .  now , it's a optional requirement .
