### ISSUE TITLE
Import fails when link instead of version is used

### ISSUE THREAD

**Issue by nickschot** [ef4/ember-auto-import#125]
Example of what goes wrong:

package.json dependencies snippet:
```json
"dependencies": {
    "ember-auto-import": "^1.2.13",
    "get-contrast-ratio": "github:nickschot/get-contrast-ratio.git#patch-1"
}
```

Gives a:
```sh
Build Error (Bundler)

Can't resolve 'get-contrast-ratio' in '/my-project'
```

This specific case is happening inside an addon (npm linked).

**Comment by ef4** [comment]
The package in that repo has an invalid `main` in its package.json. It uses a `prepublish` step to generate that file using babel. So in general, the package won't work correctly when npm-linked.

In your own fork, you can publish a branch that includes the build output and that will make it work.
