### ISSUE TITLE
Multi app build

### ISSUE THREAD

**Issue by jlami** [ef4/ember-auto-import#127]
## Summary
Auto-import needs to recognize multiple app instances to be able to make more than one bundler in the scenario that someone uses more than one EmberApp in ember-cli-build.js

## Scenario
We do the following to generate 3 apps in 1 ember build/serve in debug mode:
```js
///ember-cli-build.js
module.exports = function(defaults) {
  let app1 = new EmberApp(defaults, {
    addons: {
      //we use our own server middleware to serve the 3 apps
      //otherwise app1 will serve all requests
      blacklist: ['history-support-middleware'],
      //whitelist: [],
    },
  });
  
  let singleApp = process.env.EMBER_ENV != 'development' || process.env.SINGLE_APP;
  if (singleApp) {
    return app1.toTree();
  }
  
  let app2 = require('../app2/ember-cli-build.js')({
    project: Project.closestSync('../app2/'),
  });

  let app2 = require('../app2/ember-cli-build.js')({
    project: Project.closestSync('../app2/'),
  });

  return mergeTrees([
    app1.toTree(),
    new Funnel(app2, {destDir: 'app2', annotation: 'App2 funnel'}),
    new Funnel(app3, {destDir: 'app3', annotation: 'App3 funnel'}),
  ]);
};
```

I know this is a bit dirty, but it works. Until I used ember-intl which needed ember-auto-import to include int-relativeformat. Then only the first app will get that import. The others don't get a bundler and will error with missing dependencies.

## Side effects
It might be that ember-auto-import has some expectations on running on the 'primary' included instance. I don't see any problems right now, but I don't configure auto-import to do anything special. So this might not be the best fix in those cases.

I also saw that all the imports are gathered on one instance. So every app might get every import of the others. While this might not be bad in debug, it is still not ideal. So maybe the analyzers also have to be broken up over all the 'main' apps. While you now use the first included instance, it might be needed to find the host in those cases like you do here: https://github.com/ef4/ember-auto-import/blob/master/ts/auto-import.ts#L92

https://github.com/ef4/ember-auto-import/blob/master/ts/bundler.ts#L49
This also does some lookup to find the 'host' or root project. So maybe this should be integrated in the new application setup/split?

## Hack that makes it work
https://github.com/jlami/ember-auto-import/commit/0933b547e802951abc8d4cec0e9b87390c5e8593

Please let me know if I need to setup a simple demo.

**Comment by ef4** [comment]
The root issue is that we pick one instance of ember-auto-import to do most of the work. Right now that is global, and it's just whichever instance asks first.

To make your case work, it should be keyed off the identity of the app instance rather than global.

The relevant code is here: https://github.com/ef4/ember-auto-import/blob/ec307965ebbce248b27fb611ee0cd309056452af/ts/auto-import.ts#L20-L25

Keep in mind this coordination happens across multiple versions of ember-auto-import. Right now all versions use the same code here, but if you change it, your code needs to do the right thing if it runs before or after an older version of the code.

**Comment by jlami** [comment]
Wouldn't it be a good idea to let the lookup work from the building app, instead of a global variable?
I don't think the `appOrAddon.project` has any public api for app storage. So you would have to make that on your own. Maybe `global[protocol + appOrAddon.project.name]` could work?

The multiple versions might make things a bit difficult, that is true. But currently there is only one version in my node_modules, so my hack, or any other change to the lookup function would work.

For any future changes it might be good to see if ember-auto-import will also work as a peerDependency in addons that require it. That might make it easier to have only one version, but has some downsides too: https://github.com/ember-cli/rfcs/pull/112 and https://github.com/ember-cli/ember-cli/issues/7399

**Comment by ef4** [comment]
Yeah, I agree that peerDependency would be nice, if NPM didn't make that a terrible user experience. 

> Maybe global[protocol + appOrAddon.project.name] could work?

That is not the right semantics. It's not the `appOrAddon` we've been handed that we're trying to key off of, it's that thing's owning application. So more like `appOrAddon._findHost().project.name`. And really we should use a proper Map from the app instance directly to the AutoImport instance, without assembling string keys.

> The multiple versions might make things a bit difficult, that is true. But currently there is only one version in my node_modules, so my hack, or any other change to the lookup function would work.

Sure, but that is not relevant to what would be an acceptable PR to ember-auto-import. People absolutely will have multiple versions.

**Comment by jlami** [comment]
I don't really know if `_findHost` will get different results compared to the `.project`. I thought `project` was just a shortcut to the addon tree root. But that's not really important.

You are correct that an acceptable PR would need to work in all cases, but I'm not really sure if this is feasible at all.

Maybe it is a good idea to revisit the RFC I linked and see if we could get a better peerDependency experience? Working around a broken basis seems counterproductive.

**Comment by ef4** [comment]
> You are correct that an acceptable PR would need to work in all cases, but I'm not really sure if this is feasible at all.

I'm quite confident that it is.

> Maybe it is a good idea to revisit the RFC I linked and see if we could get a better peerDependency experience? Working around a broken basis seems counterproductive.

That is all of NPM in a nutshell. There are fundamental assumptions in NPM that cause these problems. The ember-cli RFC is a good small step. But to really make peerDependencies usable, NPM needs to resolve and install them automatically, and it doesn't.

**Comment by jlami** [comment]
> I'm quite confident that it is.

Good to hear! I was just thinking in terms of a simple PR that I could do myself. But if you are confident that you can do this, that is great. Please let me know if I can do anything smaller to help.

**Comment by jlami** [comment]
This seems fixed in recent versions
