### ISSUE TITLE
Doesn't work with ember-cli-typescript

### ISSUE THREAD

**Issue by alexlafroscia** [ef4/ember-auto-import#131]
I'm trying to use `ember-auto-import` in `ember-react-components` but am running into some issues. Instances of `react-dom` and `react` in the `app` and `test` trees seem to be found and handled, but instances in the `addon` tree as missed.

The reason I think that is this, which I found while trying to debug the problem

```
ember-auto-import:splitter output {
  "app": {
    "static": [
      {
        "specifier": "react",
        "entrypoint": "/Users/alafroscia/Code/ember/ember-react-components/node_modules/react/index.js",
        "importedBy": [
          {
            "package": "ember-react-components",
            "path": "dummy/components/basic-component.js",
            "isDynamic": false
          },
          {
            "package": "ember-react-components",
            "path": "dummy/components/functional-component.js",
            "isDynamic": false
          },
          {
            "package": "ember-react-components",
            "path": "dummy/components/invoke-action.js",
            "isDynamic": false
          },
          {
            "package": "ember-react-components",
            "path": "dummy/components/set-state.js",
            "isDynamic": false
          },
          {
            "package": "ember-react-components",
            "path": "dummy/components/using-service.js",
            "isDynamic": false
          },
          {
            "package": "ember-react-components",
            "path": "dummy/components/with-properties.js",
            "isDynamic": false
          },
          {
            "package": "ember-react-components",
            "path": "dummy/components/yield-to-children.js",
            "isDynamic": false
          }
        ]
      }
    ],
    "dynamic": []
  },
  "tests": {
    "static": [
      {
        "specifier": "testdouble",
        "entrypoint": "/Users/alafroscia/Code/ember/ember-react-components/node_modules/testdouble/lib/testdouble.js",
        "importedBy": [
          {
            "package": "ember-react-components",
            "path": "dummy/tests/unit/utils/with-ember-support-test.js",
            "isDynamic": false
          }
        ]
      }
    ],
    "dynamic": []
  }
} +0ms
```

No entry for `addon` in there.

The result is that my tests fail because the `react` and `react-dom` imports in `addon` are not transformed and thus the modules cannot be found.

One thing that might be related: the addon uses `ember-cli-typescript` for the files in `addon`. Do I need to configure anything in `ember-auto-import` to search the TypeScript files? Since `ember-auto-import` is already configured to run after `ember-cli-typescript`, I assume that isn't the issue, but figured it was of note at least.

**Comment by jamescdavis** [comment]
It is likely that `ember-cli-typescript` *is* causing the issue because it does [weird things](https://github.com/typed-ember/ember-cli-typescript/blob/3503e8041db6cab98b06085f5ec6934644558fad/ts/addon.js#L90-L99) for addons that prevent `ember-auto-import` from ever seeing the addon tree. This *should* be fixed when we move to letting Babel 7 handle the transpilation.

**Comment by BryanCrotaz** [comment]
Is there a workaround?

**Comment by BryanCrotaz** [comment]
and can we get something in the docs that says this doesn't work for addons written with ember-cli-typescript? I just lost 2 days trying to work out why my import wasn't working

**Comment by BryanCrotaz** [comment]
**WORKAROUND**
```
// addon/components/my-component.ts
import something from 'something'; // a non-ember module
...

// app/components/my-component.ts
import something from something; // this is the one that ember-auto-import can see

console.log(something); // we have to use something otherwise the compiler strips it out and then ember-auto-import can't see it
export { default } from 'my-addon/components/my-component'
```

**Comment by NullVoxPopuli** [comment]
is this still an issue?

**Comment by ef4** [comment]
Not as far as I know.
