### ISSUE TITLE
Error when using with apollo-link-schema

### ISSUE THREAD

**Issue by FabianHoffmann** [ef4/ember-auto-import#135]
Hi,

I want to use ember-auto-import for the package [apollo-link-schema](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-schema). 

When I include the package like this:

`import { SchemaLink } from 'apollo-link-schema';`

I get the following error when running the project:

> Error while processing route: index Could not find module `./../../process/browser.js` imported from `(require)` Error: Could not find module `./../../process/browser.js` imported from `(require)`
> router.js:931
>     at missingModule (http://localhost:4200/assets/vendor.js:252:11)
>     at findModule (http://localhost:4200/assets/vendor.js:263:7)
>     at requireModule (http://localhost:4200/assets/vendor.js:29:15)
>     at eval (webpack://__ember_auto_import__/./node_modules/graphql/jsutils/instanceOf.mjs?:34:41)
>     at Module../node_modules/graphql/jsutils/instanceOf.mjs (http://localhost:4200/assets/vendor.js:100386:1)
>     at __webpack_require__ (http://localhost:4200/assets/vendor.js:102278:30)
>     at eval (webpack://__ember_auto_import__/./node_modules/graphql/type/definition.mjs?:46:77)
>     at Module../node_modules/graphql/type/definition.mjs (http://localhost:4200/assets/vendor.js:100710:1)
>     at __webpack_require__ (http://localhost:4200/assets/vendor.js:102278:30)
>     at eval (webpack://__ember_auto_import__/./node_modules/graphql/type/validate.mjs?:4:69)

Is there any way to fix this? I appreciate any advice.

**Comment by ef4** [comment]
I was not able to reproduce this, I added these to an app and your import line worked for me:

```
"apollo-link-schema": "^1.1.1",
"ember-auto-import": "^1.2.13",
"graphql": "^14.0.2",
```

**Comment by FabianHoffmann** [comment]
Thank you for your time, it was indeed my mistake. I was missing "graphql" in devDependencies.
