### ISSUE TITLE
Addon issue

### ISSUE THREAD

**Issue by maxwondercorn** [ef4/ember-auto-import#145]
ember auto import is a great addon and I've used it in several projects - thanks.  I'm trying to use it in to convert an addon from bower to npm without success.  Considering how easy it is to use, I'm sure I'm missing something basic.

The required packages are in the [addon's](https://github.com/maxwondercorn/ember-c3) dependencies and the test app works without issue.
```
  "dependencies": {
    "c3": "^0.6.8",
    "d3": "^5.7.0",
    "ember-auto-import": "^1.2.15",
    "ember-cli-babel": "^6.6.0"
  },
```

c3 is the direct import but a `Could not find module 'c3'` error message is generated.  I threw my test [app](https://github.com/maxwondercorn/import-test) to github

While I can use ember-cli-cjs-transform in this application, the preference is auto import

**Comment by ef4** [comment]
Thanks for sharing the code, that makes it easy to debug. I PRed the fix to your ember-c3 fork.

**Comment by rwwagner90** [comment]
What was the fix in question here? I'm getting a similar cannot find module message in my addon.

**Comment by maxwondercorn** [comment]
Let me see if I can find it in my repo.  I deleted the test fork

**Comment by rwwagner90** [comment]
I found it. It was calling super in the included hook. My problem randomly went away, so we're good 👍

**Comment by maxwondercorn** [comment]
Fix in index.js line 2 from:
```
  included: function(app) {		   
     this._super.included(app);		
     app.import("node_modules/c3/c3.css");
   }
```

to: 
```
  included: function(app) {		   
     this._super.included.apply(this, arguments);	
     app.import("node_modules/c3/c3.css");
   }
```

**Comment by ef4** [comment]
Thanks. I [added this to the README](https://github.com/ef4/ember-auto-import/commit/d7aae41b40158dc9d4e91e268f574cc1b91c8544) but should have left more detail in this issue too for future travelers.
