### ISSUE TITLE
Package is loaded from the main entry point instead of browser in package.json

### ISSUE THREAD

**Issue by Subtletree** [ef4/ember-auto-import#149]
I'm loading the package https://github.com/dtjohnson/xlsx-populate with ember-auto-import.

It's package.json specifies:
```
"main": "lib/XlsxPopulate.js",
"browser": {
  "XlsxPopulate": "./browser/xlsx-populate.js"
},
```
However It fails with:
```
[./node_modules/xlsx-populate/lib/XlsxPopulate.js] 2.29 KiB {vendors~app} [built]

ERROR in ./node_modules/xlsx-populate/lib/Workbook.js
Module not found: Error: Can't resolve 'fs' in '/Users/ryanscott/projects/loan_crm/node_modules/xlsx-populate/lib'
 @ ./node_modules/xlsx-populate/lib/Workbook.js 4:11-24
 @ ./node_modules/xlsx-populate/lib/XlsxPopulate.js
 @ ./tmp/bundler-cache_path-flHgouPv.tmp/staging/app.js
 @ multi ./tmp/bundler-cache_path-flHgouPv.tmp/staging/l.js ./tmp/bundler-cache_path-flHgouPv.tmp/staging/app.jsBuild Error (Bundler)
```

So it seems like it's using `main` as an entry point instead of `browser`.

Everything works when I use:
```
autoImport: {
  alias: {
    'xlsx-populate': 'xlsx-populate/browser/xlsx-populate'
  }
}
```

Should it be loading from browser by default?

ember-auto-import v1.2.15

**Comment by ef4** [comment]
We do prioritize `browser` over `main`, but in this case the package is trying to export a name that is different from the NPM package name. That won't work here.

I think either of these would have worked:

```
"main": "lib/XlsxPopulate.js",
"browser": {
  "xlsx-populate": "./browser/xlsx-populate.js"
},
```

Or

```
"main": "lib/XlsxPopulate.js",
"browser": "browser/xlsx-populate.js"
```

Using `alias` is the best choice for you as the consumer of the library.

**Comment by Subtletree** [comment]
Thank you!

❤️  e-auto-import
