### ISSUE TITLE
Add config to disable fastboot js/map creation

### ISSUE THREAD

**Issue by Alonski** [ef4/ember-auto-import#150]
Currently this addon creates the files `auto-import-fastboot.js` and a map for it.

If an app doesn't use fastboot it has no need for these, I assume.

We should add a config to allow disabling the generation of these files.

Relevant files:
https://github.com/ef4/ember-auto-import/blob/master/ts/bundler.ts#L138
https://github.com/ef4/ember-auto-import/blob/master/ts/auto-import.ts#L131

**Comment by ef4** [comment]
It shouldn't even need a config I think, we should be able to see if the app includes ember-cli-fastboot.

**Comment by Alonski** [comment]
Good idea @ef4 I don't know when I'll find the time to do this but I'll try in the coming weeks

**Comment by ef4** [comment]
You can check for ember-cli-fastboot the same way we already locate ember-cli-babel. See:

https://github.com/ef4/ember-auto-import/blob/d7aae41b40158dc9d4e91e268f574cc1b91c8544/ts/package.ts#L44

and

https://github.com/ef4/ember-auto-import/blob/d7aae41b40158dc9d4e91e268f574cc1b91c8544/ts/package.ts#L54-L56

**Comment by Alonski** [comment]
@ef4 Can you assign this to me please?

**Comment by houfeng0923** [comment]
execute me , is it ready now or later?

**Comment by Alonski** [comment]
@houfeng0923 I still haven't done this 😅

**Comment by houfeng0923** [comment]
@Alonski 
no matter, i send a pull request just now .

**Comment by jamescdavis** [comment]
closed by #271

**Comment by jamescdavis** [comment]
Resolved in release 1.6.0
