### ISSUE TITLE
WARNING: unable to read package.json for ember-auto-import, including stage 1 decorators by default

### ISSUE THREAD

**Issue by boris-petrov** [ef4/ember-auto-import#162]
I have no idea what this means, it started appearing after I updated to 1.2.18. Everything still seems to work fine but this message didn't appear on 1.2.17. Should I be worried? :)

**Comment by ef4** [comment]
This search shows us where it's coming from: https://emberobserver.com/code-search?codeQuery=including%20stage%201%20decorators%20by%20default

https://github.com/ember-decorators/ember-decorators/blob/f6259d7e38e25f60d249e8771f340b89e50dc42f/packages/utils/index.js#L46

This is a bug in ember-decorators, I see why, I will make a PR for them.

**Comment by musaffa** [comment]
@ef4 The fix has been released in ember-decorators v3.1.5 but the warning still shows up.
