### ISSUE TITLE
Help understanding how to work with CommonJS modules

### ISSUE THREAD

**Issue by samselikoff** [ef4/ember-auto-import#165]
I noticed the Readme says things should mostly just work with CommonJS modules, so I'm wondering if I'm doing something wrong.

I'm trying to use Auto Import to get [Remarkable](https://github.com/jonschlinkert/remarkable) into an Ember component.

After adding `remarkable` to my `devDependencies` and running `ember install ember-auto-import`, I try this from a component:

```
import Remarkable from 'remarkable'
```

and get an error that the module could not be found.

In the Customizing Build Behavior section I see the `alias` option with this example:

```
'plotly.js': 'plotly.js-basic-dist'
```

This makes me wonder if I should be doing `import Remarkable from 'remarkable.js'`? But that doesn't work either.

I also saw

```
'handlebars': 'handlebars/dist/handlebars'
```

so I tried doing

```
'remarkable': 'remarkable/dist/remarkable'
```

to no avail.

Any suggestions? After I figure it out I'd be happy to PR the Readme to help future travelers!

**Comment by ef4** [comment]
Using ember-auto-import 1.2.18 and remarkable 1.7.1 this worked for me on the first try.

Please rule out interference from other JS preprocessor addons.

**Comment by samselikoff** [comment]
Sorry, should have tried to reproduce. Looking into it, and thank you!

**Comment by samselikoff** [comment]
Working, thank you!
