### ISSUE TITLE
Importing 0x.js

### ISSUE THREAD

**Issue by leoplct** [ef4/ember-auto-import#17]
ember install ember-auto-import
npm install 0x.js --save-dev

and put this into application.js controller (btw where is best place to have it globally available?)

import { ZeroEx } from '0x.js';

but if I log in console "ZeroEx" is undefined

**Comment by ef4** [comment]
Thanks for reporting this bug. It looks like 0x.js depends on a lot of node-specific things that Rollup can't easily package. I was able to get further by adding some additional rollup plugins, but I think it depends on some modules that can't run in strict mode, which means Rollup is going to have a hard time with them.

It looks like 0x.js uses webpack when they build their UMD package, which makes me think we can solve this by adding a webpack-based strategy to ember-auto-import.

**Comment by ef4** [comment]
I think this is fixed in 0.2.2 where I made webpack the default.

**Comment by leoplct** [comment]
If I try to import it, the object ZeroEx is undefined

**Comment by leoplct** [comment]
Removed node_modules and updating all and it works.
Thank you
