### ISSUE TITLE
Limitations for addons

### ISSUE THREAD

**Issue by Jbcampbe** [ef4/ember-auto-import#171]
> ember-auto-import will refuse to import devDependencies of your addon, for the same reason. Whatever you're importing must be in dependencies

This requirement for addons makes a lot of sense but I have run into a few cases where it can be problematic. 

The first case was when using `d3`. I would like to be able to just have the main `d3` library as my dependency in package.json but then import directly from the submodules (for example `import { scaleLinear } from "d3-scale";`. At the moment I can't do this because `d3-scale` is not listed in my package.json. I have to `import d3 from 'd3'` which brings in the entire library. 

The second case was when trying to import a dependency that I used only in tests (in my case `lolex`). I don't want to have to list this as a dependency since it isn't needed by consumers.

Is there a way to fix these cases or does a workaround already exist that I just missed?

Thanks

**Comment by ef4** [comment]
> The second case was when trying to import a dependency that I used only in tests (in my case lolex). I don't want to have to list this as a dependency since it isn't needed by consumers.

This is the easier part of your question. You're allowed to use devDependencies in your own tests (and anywhere in your dummy app). So yes, you're correct that you should put things into devDependencies if your tests need them but your consumer's apps don't. This should already work correctly in ember-auto-import.

> The first case was when using d3. I would like to be able to just have the main d3 library as my dependency in package.json but then import directly from the submodules (for example import { scaleLinear } from "d3-scale";

`d3-scale` is in `dependencies` of `d3`. That has a clear meaning in NPM, and that meaning _does not_ include letting consumers of `d3` "look inside" and use `d3-scale`. If you want to use `d3-scale`, it needs to be one of _your_ dependencies. 

It's true that node_modules resolution rules will _sometimes_ allow you to access your dependencies' dependencies, but this _is not guaranteed and not safe to rely on_. The d3 documentation is somewhat misleading on this point, it seems to imply you can just add d3 and then require d3-scale, and that's just not true.

You should either depend on `d3` and import from `d3`, or depend on `d3-scale` and import from `d3-scale`.

**Comment by Jbcampbe** [comment]
I see that makes sense. Thanks @ef4!
