### ISSUE TITLE
dynamic import in firefox

### ISSUE THREAD

**Issue by mcfiredrill** [ef4/ember-auto-import#173]
I noticed dynamic import didn't seem to be working in Firefox, and caniuse tables seem to confirm that its not supported yet.
https://caniuse.com/#feat=es6-module-dynamic-import

I know this isn't specific to ember-auto-import, but I was wondering if there was any sort of polyfill or work around yet?

Thanks for reading.

**Comment by ef4** [comment]
This is a misunderstanding of how ember-auto-import works. All imports (static and dynamic) are transpiled away during the build. No native browser support is required.

**Comment by ef4** [comment]
Which is to say: if you have a reproducible problem on Firefox, please share details, because it's supposed to work.

**Comment by mcfiredrill** [comment]
Thanks for the fast response.

So ok, yeah I believe I am getting this problem on Firefox. Seems to only be happening in production.
```
GET
https://datafruits.fm/assets/chunk.fcf3bebbdb064138465a.js
[HTTP/2.0 522 No Reason Phrase 17982ms]
GET
https://datafruits.fm/assets/chunk.c2d0924a543ecba02868.js
[HTTP/2.0 522 No Reason Phrase 17995ms]
Loading failed for the <script> with source “https://datafruits.fm/assets/chunk.fcf3bebbdb064138465a.js”.
chat:1
Loading failed for the <script> with source “https://datafruits.fm/assets/chunk.c2d0924a543ecba02868.js”.
chat:1
Error: Loading chunk 3 failed.
(error: https://datafruits.fm/assets/chunk.fcf3bebbdb064138465a.js)
vendor-a0e410f8704357f994cd3a819f4bf5ae.js:10739:91
```
relevant code:
https://github.com/datafruits/datafruits/blob/master/app/components/datafruits-visuals.js#L36

I'll try to reproduce a stand alone example.

**Comment by NullVoxPopuli** [comment]
I have dynamic import working in firefox -- can this issue be closed?
