### ISSUE TITLE
Ideas for testing an import

### ISSUE THREAD

**Issue by samselikoff** [ef4/ember-auto-import#184]
Hey there :)

I've been poking around your tests, and I'm wondering if you have a clever idea for testing an import.

In Mirage, I'm adding the ability for users to provide their own versions of Pretender. If they don't, Mirage will fallback to some default version it depends on.I'd like to write a test to verify this works.

I found [this test](https://github.com/ef4/ember-auto-import/blob/master/packages/sample-conflict/ensure-failed-build.sh) which ensures the build fails, but in my case, I'd like to use a sample package and ensure the "local" version of Pretender gets included into the client-side build.

Do you have any ideas for how I could do this? I saw your [change-package-version](https://github.com/ef4/ember-auto-import/blob/master/scripts/change-package-version.js) script copies the root version of a dep, and changes the version for the local project. I could do something similar, but how might I assert that _that_ version ended up in the clientside build?

Been banging my head against this so figured I'd ask here. Thanks for any info! Feel free to close this at any time.

**Comment by ef4** [comment]
Hmm. I guess it depends on your implementation. You will need to cover both the positive cases (_some_ version of pretender is present) and the negative ones (there's not a duplicate copy in the build). These are pretty different and may need different strategies.

You can write a test that runs a full `ember build` and then inspects the resulting artifacts. Like, you can actually search for a string in vendor.js if that helps, and make sure it's not there twice. Or you can mock the version of pretender and replace it with code that is easily detectable by a test.

How are you actually implementing this? Are you attempting to use ember-auto-import to get pretender in both cases?

**Comment by samselikoff** [comment]
Right now the implementation uses [`npmAsset`](https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L24) and a [Pretender shim](https://github.com/samselikoff/ember-cli-mirage/blob/master/vendor/ember-cli-mirage/pretender-shim.js), so as part of this work I'd love to modernize it using ember-auto-import. In that case would your recommendation change?

Re: inspecting the artifacts, is it possible to see the `version` that came from `package.json` there? If now, how could I reliably modify/mock the version of pretender and assert against it in the test? I guess just literally mock the object with whatever Mirage relies on to initialize...

**Comment by samselikoff** [comment]
I haven't considered going all the way to a yarn workspace/monorepo yet, I'm still on the setup you used to have with multiple projects under `/test-apps` and a `link-them` script. In that case, could I use a `file: '../..'` value in my test app's `package.json` entry for pretender? Or, where could I learn more about version resolution?

**Comment by ef4** [comment]
Ah, so I actually moved all the way to a full monorepo. The deciding factor was the desire to have conflicting versions in different test apps (particularly ember-cli-babel 6 vs 7).

**Comment by ef4** [comment]
Oh, I see you said "used to have", so you knew that.

**Comment by samselikoff** [comment]
right. How has that been?

**Comment by ef4** [comment]
It's fine. I do miss having my actual addon at the repo root sometimes, but that's a small thing.

Back to your question, the thing to remember about how package.json effects node package resolution is that it has zero impact at runtime. Any impact it has happens during `npm install`.  For example `file:` works, but it works by making a copy at `npm install` time. At runtime, resolution always follow the standard node_modules algorithm (and finds the copy). So in the context of tests, changing package.json isn't likely to help much, and you're better off just making copies or symlinks directly.

But all of this feels like you're fighting hard against a general NPM problem that isn't really a mirage concern. In a reasonably-sized app there are dozens of dependencies that could get duplicated. Pretender isn't special in that regard.

**Comment by samselikoff** [comment]
I'm moving over to ember-auto-import, and things to be going well so far (🙌)

> You will need to cover both the positive cases (some version of pretender is present) and the negative ones (there's not a duplicate copy in the build). These are pretty different and may need different strategies.

The positive case is covered by my normal acceptance tests – I can see them working right now after adding `ember-auto-import` (after they were previously failing). The only thing left is to get the negative case.

Now that I'm using `ember-auto-import`, anything special I need to know before trying to point my sample-app to a different version of pretender? (I was going to try that by doing the linking script, moving something to `/test-projects/01-basic-app/node_modules/.bin`, for example a mock of Pretender).

**Comment by samselikoff** [comment]
I get that this is a more general NPM problem, but does ember-auto-import have any functionality for specifying which version should "win"?

**Comment by ef4** [comment]
That is definitely not in scope. The whole point is to faithfully do the same thing NPM would do.

**Comment by samselikoff** [comment]
Ya, makes sense. 

So in your own projects have you encountered this situation, where you need to guarantee one version of a dep “wins”? If so how did you handle it?

**Comment by buschtoens** [comment]
I think this intersects with https://github.com/ef4/ember-auto-import/issues/170#issuecomment-449123743.

What do you think about declaring `pretender` as a `peerDependency` and then [adding it as a dependency to the project](https://ember-cli.com/api/classes/Blueprint.html#method_addPackageToProject) in the installation blueprint?

**Comment by samselikoff** [comment]
I have been told `peerDependencies` are not enforceable. They also seem to not be used widely throughout the ecosystem – every addon has a `peerDependency` on `ember-source` but I have not seen that declared by any package. The `ember-jquery` approach appeals to me because 90%+ of Mirage users will never care to configure Pretender, and they won't have to manage it in their `package.json`.

**Comment by ef4** [comment]
They're enforceable, just not by the `npm` command. You can make mirage refuse to build if a peer dep isn't present. But yes, when npm designed peer deps they did a terrible job, which is why they're rarely used correctly or at all.

Given that you think this is an advanced, 10% of users case, I think you should use the broadest supported dependency range (like `"pretender": ">1"`), import it with ember-auto-import, and then not worry any more about it. This gives the advanced users a good shot of being able to deduplicate, and it makes things totally automatic for everyone else.

**Comment by samselikoff** [comment]
Hmm. That's certainly more appealing than [this rubbish](https://github.com/samselikoff/ember-cli-mirage/pull/1471/files#diff-168726dbe96b3ce427e7fedce31bb0bcR91) I have going on in a PR right now...

How best to test, use `ember-try` with different versions of pretender? Use one of my test-projects with a copied older version of pretender? Or should I not bother about testing at all (since this is really like "testing the framework")?

**Comment by ef4** [comment]
I meant a one-time test. I'm suggesting this dep isn't special. You don't need to continually test the older versions because they aren't changing.

**Comment by samselikoff** [comment]
Makes sense. I think I get the "this dep isn't special" point now. So basically, any dep that is an "implementation detail" of Mirage, but then "is promoted" to more than that on account of the host app wanting control over its version, could be user-configured in this way. Basically, if they specify it, it should work + override the one Mirage specifies (with the normal caveat about all the existing issues in the tooling/npm layers).

So if someone comes asking about wanting to use a new version of `whatwg-fetch`, they could do the same thing – install it as a dep of their own project and Mirage should import and use that one. Is that more or less correct?

**Comment by ef4** [comment]
Yes, as long as the version they want to use is allowed by your own dependency range. Hence the need to make it as broad as you can.

**Comment by samselikoff** [comment]
Thanks again! I owe you a 🍺.

**Comment by Turbo87** [comment]
> You don't need to continually test the older versions because they aren't changing.

I'm not sure I agree. At some point in time this would be correct, but let's say you start using a newer API from the dependency, but you don't realize that it's not available in the older versions that you still claim to support. Your tests against the newest version would work fine then, but in reality it would stop working for anyone still using the older dependency version.

Rust's `cargo` has an experimental mode where they resolve all dependencies to the lowest allowed version, but actually trying that has shown that almost nothing works anymore afterward. In `npm` I would expect the same breakages if `yarn` had such functionality, just not as obvious as most of it isn't that strictly typed.

**Comment by samselikoff** [comment]
@ef4 In the case of Ember CLI Tailwind, it is closer to the 90% case where users would care about their Tailwind version. If I could snap my fingers then, I suppose I would ensure Ember CLI Tailwind works with multiple versions of Tailwind, specify that liberally in the `dependencies` section, and allow people to override by just installing their own?

Or is this be a case where using `addPackagesToProject`, `peerDependencies` and coding Ember CLI Tailwind to fail the build if it doesn't find a `tailwind` package be the better approach?
