### ISSUE TITLE
forbidEval in app's ember-cli-build.js doesn't affect ember-auto-import in dependency addons

### ISSUE THREAD

**Issue by DuBistKomisch** [ef4/ember-auto-import#187]
Following on from #50 and #139.

We're only using `ember-auto-import` via `ember-intl`, not directly in our app. Setting `autoImport: { forbidEval: true }` in our `ember-cli-build.js` doesn't seem to prevent it from using `eval`, generating dozens of CSP errors in development.

Is it possible for the setting to flow down like this? Do we need to add `ember-auto-import` as a direct dependency too to make it work? Is this something `ember-intl` has to fix instead?

**Comment by ef4** [comment]
`forbidEval` is supposed to only be controlled by apps, not addons. So it's not something to fix in ember-intl. 

You're right, we need to add the ability for apps to set this even when the app itself isn't directly using auto-import.

As a workaround, I think it should work to add ember-auto-import as a dependency to your app and then it will respect your setting.

**Comment by DuBistKomisch** [comment]
Thanks, I'll try adding it as a dependency.

**Comment by DuBistKomisch** [comment]
Late reply, but adding as a direct dependency does seem to work. Guess it's time to finally migrate from `ember-browserify`!

**Comment by ef4** [comment]
This is dependent on https://github.com/ef4/ember-auto-import/issues/196

**Comment by simonihmig** [comment]
I just had the same problem, but for me `forbidEval` had no effect even though the app is already using `ember-auto-import`. I am using `ember-cli-mirage` (which depends on e-a-i as well), and a whole lot of its imports (of `miragejs`) can be found in `test-support.js` as `eval()`! 🤔

**Comment by ef4** [comment]
@simonihmig the original issue above got fixed in #213, if you're still seeing this please file a new issue.
