### ISSUE TITLE
Installing Auto Import breaks tests

### ISSUE THREAD

**Issue by samselikoff** [ef4/ember-auto-import#189]
After installing Ember Auto Import into Ember CLI Addon Docs, the test suite won't run.

I'm on `master`, everything's clean, tests pass. I run

```
ember install ember-auto-import
```

and run `ember t`, and I get this error:

```
not ok 1 Chrome 71.0 - [undefined ms] - Global error: Uncaught Error: QUnit has already been defined. at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 2896
    ---
        Log: |
            { type: 'error',
              testContext: {},
              text:
               'Uncaught Error: QUnit has already been defined. at webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?, line 2896\n' }
    ...
not ok 2 Chrome 71.0 - [undefined ms] - Global error: Uncaught Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 2137
    ---
        Log: |
            { type: 'error',
              testContext: { state: 'complete' },
              text:
               'Uncaught Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 2137\n' }
```

(Related to https://github.com/ef4/ember-auto-import/issues/188, I thought the error there was related to what I was doing but it came just from installing Auto Import).

**Comment by samselikoff** [comment]
Think I figured it out, we have both `ember-cli-qunit` and `qunit` in our `package.json` file.

**Comment by samselikoff** [comment]
Believe Auto Import is seeing 

```
import { module, test } from 'qunit';
```

from my test-app and its causing it to go hunt for the `qunit` module in package.json (when it's already being included by `ember-cli-qunit`. We do want `qunit` in there as well for some node tests.

I do think this is a weird setup but, so I don't have to refactor this all right now, is there a way to tell Auto Import to ignore these?

Answer: Readme says there is! Trying it out.

**Comment by samselikoff** [comment]
Worked! https://travis-ci.org/ember-learn/ember-cli-addon-docs/builds/492415520

**Comment by ef4** [comment]
Yeah, sorry, qunit was the original motivating example for `exclude`.
