### ISSUE TITLE
Synchronous dynamic imports

### ISSUE THREAD

**Issue by bobisjan** [ef4/ember-auto-import#194]
Hello 👋,

we are using `import()` for lazy loading with great success, many thanks for that ❤️.

Currently we are facing a situation how to synchronously reuse already imported dynamic module. We use service ATM to solve this problem, but would it make sense to provide some kind of `importSync()` method from `ember-auto-import`?

```javascript
// in route.js
model() {
  return import('foo');
}

// some deeply nested component from that route
didInsertElement() {
  importSync('foo').default();
}
```
Thanks

**Comment by ef4** [comment]
I think what you’re doing with your own service is probably best. 

I don’t think we should invent nonstandard language features in ember-auto-import. (Everything we have now is standards compliant.)

**Comment by bobisjan** [comment]
Thanks, being standards compliant makes sense to me 👍.

Using custom service is good enough, it just adds extra layer on top of `import()`.
