### ISSUE TITLE
Always check for app-level configuration

### ISSUE THREAD

**Issue by ef4** [ef4/ember-auto-import#196]
Right now, to affect auto-import's configuration you must depend (directly) on auto-import. But sometimes you have a need to affect the configuration (as used by your dependencies) even though you don't otherwise need or want a direct dependency on auto-import.

For example, a setting like `forbidEval` only belongs at the app level, it would not be appropriate on an addon. But an app that depends on an addon that uses ember-auto-import may still want to express that it needs `forbidEval`, even though the app itself doesn't have a direct dependency on auto-import.

We should always check for configuration on the app.

**Comment by stefanpenner** [comment]
does https://github.com/ef4/ember-auto-import/pull/213 close this?

**Comment by ef4** [comment]
Yes, this is fixed.
