### ISSUE TITLE
Insanely slow builds with ember version 3.4+

### ISSUE THREAD

**Issue by nerdybeast** [ef4/ember-auto-import#198]
I tried upgrading my ember app from 3.3.0 to the latest version (currently 3.8.0) but after doing so my build was failing.  After asking the almighty Google, I realized I needed to update ember-auto-import as well.

It looks like the minimum version of ember-auto-import needed for ember version 3.4+ is 1.2.12 but using this version OR any higher version is causing my app builds to be several minutes.

I have created a repo that reproduces this issue: https://github.com/nerdybeast/slow-ember-build.git

Simply clone, npm install, and run ember serve. This will take 2+ minutes for the build to complete and that same amount of time for each file change.

**Comment by nerdybeast** [comment]
I opened an issue with ember cli for this same thing as I was unsure where the problem is occurring and they seemed to think the issue is on this side.

https://github.com/ember-cli/ember-cli/issues/8472

**Comment by igbopie** [comment]
Same issue after upgrading

**Comment by igbopie** [comment]
I think the problem is in the `bundlerHook`. I am taking a look.

**Comment by igbopie** [comment]
Actually, downgraded `ember-cli-mirage` and that got rid of `ember-auto-import`. :)

**Comment by ef4** [comment]
Thank you @nerdybeast for providing a runnable reproduction. It helped me rule out several possible sources of slowness.

What I discovered is that it's the presence of at least one `app.import` from a large package like `material-design-icons` (which is 356 MB!) is the trigger for the slowness.

But this also has nothing to do with ember-auto-import. If I remove ember-auto-import entirely from https://github.com/nerdybeast/slow-ember-build.git, the build stays just as slow.

I will comment on the ember-cli issue. If somebody shares a different reproduction that gets fast just by removing ember-auto-import, I will reopen this one.

**Comment by igbopie** [comment]
Yes, actually, after removing ember-auto-import, build is still slow in my case too.
