### ISSUE TITLE
Feature request: Work for nested addons

### ISSUE THREAD

**Issue by cibernox** [ef4/ember-auto-import#2]
I have an addon that wants to import and use `luxon`.

If `ember-auto-import` and `luxon` are both dependencies of the addon (not `devDependencies`), addon code importing `luxon` should work and also app code should be able to import things from `luxon`

:+1:/:-1:

**Comment by offirgolan** [comment]
This sounds pretty sketchy if you ask me. If you need to use `luxon` in your app, you should add it as a dependency of your app. Depending on the addon's dependency can cause a lot more harm in the long run. For instance, if the addon removed `luxon` as a dependency or upped to a major version with breaking changes, you are kinda screwed. Not only that, figuring out where the `luxon` issues are coming from will be a nightmare.

**Comment by ef4** [comment]
It’s not any more sketchy than how things already work when an addon needs to do app.import. 

It’s also analogous to how npm works most of the time. Your dep’s deps get hoisted, which means your app is actually able to directly require them. We defend against that kind of extraneous require via an eslint rule, and a similar rule could be made to work in clientside code.

**Comment by offirgolan** [comment]
> It’s not any more sketchy than how things already work when an addon needs to do app.import.

Agreed. 

> It’s also analogous to how npm works most of the time. Your dep’s deps get hoisted, which means your app is actually able to directly require them.

Also agreed. I just think that importing from a dep's dep that you are not directly depending on is sketchy.

**Comment by offirgolan** [comment]
> However right now, even imports from within addon code don't work. That much at least should work.

Ah ~ Didn't know that! Totally with agree with that 😄

**Comment by robclancy** [comment]
This also means it doesn't work on in-repo engines? I never got any luck with it so I assume it's the same issue since they are basically the same thing.
