### ISSUE TITLE
Trouble when linking addons

### ISSUE THREAD

**Issue by Jbcampbe** [ef4/ember-auto-import#202]
Locally whenever I npm link my addon the app build almost always fails with an error.

`Error: <host-app> and <my-addon> are using different versions of <library>`

Usually the library versions are only off by a patch bump. But when I have a lot of libraries being imported it can be very time consuming getting all of the library versions to line up between the host and addon. And life gets even more painful when I need to link 2+ addons to the host (which I do have to do frequently for work). 

Is there any way for the auto import to automatically resolve the library version difference if the two versions are semver compatible (according to the host apps package.json)?

Being able to automatically resolve these issues would dramatically improve the addon development experience.

**Comment by ef4** [comment]
I agree, we can make this better.

We can tolerate the presence of multiple versions as long as they satisfy the semver requirements of all consumers.

**Comment by Jbcampbe** [comment]
Is this change on the roadmap at all? As we have moved to using ember-auto-import for everything this error is becoming more and more common

**Comment by ef4** [comment]
The condition that needs to change is here if somebody wants to have a go:

https://github.com/ef4/ember-auto-import/blob/e7d34659666ece3a33c822971e12720680b86c89/packages/ember-auto-import/ts/splitter.ts#L148

**Comment by miguelcobain** [comment]
@ef4 what is needed to move this forward in 2021?
Is it just a matter of changing that condition to a more relaxed and semver friendly one?

**Comment by ef4** [comment]
@miguelcobain I started trying to write instructions and it was harder than just doing it. 😁

**Comment by miguelcobain** [comment]
Thank you! 🙌
