### ISSUE TITLE
1.3.0 published on npm

### ISSUE THREAD

**Issue by CvX** [ef4/ember-auto-import#207]
There is version 1.3.0 unintentionally (I assume) published on npm, without a readme (https://www.npmjs.com/package/ember-auto-import/v/1.3.0) and containing `yarn-error.log` file generated on @ef4's machine.

**Comment by ef4** [comment]
It's a valid release. 

We haven't published README's in the NPM tarball since switching to a monorepo. Should we?

The error log was unintentionally included, but also not harmful.

**Comment by Turbo87** [comment]
@ef4 I think the main confusion comes from the release/tag not being pushed to GitHub for some reason

**Comment by CvX** [comment]
Yeah, the missing release and tag, no mention of this version in the CHANGELOG.md on master, and no recent commit that would match this release, and that error log, all lead me to believe that it was a release accidentally triggered by running some script locally. 😉

**Comment by ef4** [comment]
Ah, I didn't notice the unpushed tag & commit. Pushed now, thanks.
