### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by williamhaley** [ef4/ember-auto-import#212]
I have installed `ember-auto-import`

```
ember install ember-auto-import
```

I then installed lodash

```
yarn add --dev lodash-es
```

I tried including lodash in a model

```
import { capitalize } from 'lodash-es';
```

And I get back this error in my browser

```
Error: Could not find module `lodash-es` imported from `the component...`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:422)
    at Class.resolveOther (index.js:101)
    at Class.resolve (index.js:163)
    at resolve (container.js:1197)
    at Registry.resolve (container.js:737)
```

I also tried the same with `d3` and `moment`, but I keep seeing errors.

```
Error: Could not find module `d3` imported from `the component...`
```

I feel like I must be missing something very basic. I know `ember-auto-import` is set up as the [zero config preferred way from the Ember docs/guides to import regular npm packages](https://guides.emberjs.com/release/addons-and-dependencies/managing-dependencies/), but I must be missing something or my setup is busted.

I tried running with debugging like so

```
DEBUG="ember-auto-import:*" ember s
```

I see output for `ember-auto-import`, and I _think_ I see `d3` in this case being detected like I'd hope.

```
  ember-auto-import:splitter output {
  "app": {
    "static": [
      {
        "specifier": "d3",
        "entrypoint": "/app/node_modules/d3/index.js",
        "importedBy": [
          {
            "package": "some app",
            "path": "some model.js",
            "isDynamic": false
          }
        ]
      },
```

Is there something about the import syntax I'm doing wrong?  This is how the [d3 README suggests importing](https://github.com/d3/d3) claims it could be imported.

```
import * as d3 from "d3";
```

**Comment by ef4** [comment]
I just tested and in a new ember app both those examples work. There must be an interaction with something else in your app.

The debug output implies that we're successfully detecting the need for `d3`. If you search through your `vendor.js`, does it seem to contain d3?

**Comment by williamhaley** [comment]
Sorry, it's due to CSP on my setup. I _knew_ that was a caveat that was [clearly called out](https://github.com/ef4/ember-auto-import#i-use-content-security-policy-csp-and-it-breaks-ember-auto-import) in the `ember-auto-import` README, but I still screwed this up.

I would've sworn I added the proper config in my `ember-cli-build.js`, but after deleting all my app files (except my `application.js` controller) and every plugin and slow re-introducing plugins to find the culprit, it's clear that CSP was at fault for me and updating the config as directed by the README solved my problem.

    autoImport: {
      forbidEval: true,
    }

Sorry to waste your time 😞
