### ISSUE TITLE
Analyzer fails on TS declaration file with multiple ambient declarations importing the same thing

### ISSUE THREAD

**Issue by csantero** [ef4/ember-auto-import#220]
Given a .d.ts file with multiple ambient declarations that perform the same import:

```
declare module 'my-app/something-1' {
  import { Something } from 'somewhere';
  export default function something1(): Something;
}

declare module 'my-app/something-2' {
  import { Something } from 'somewhere';
  export default function something2(): Something;
}
```

I get the following error with ember-auto-import 1.4.0 (and ember-cli-typescript 2.0.1):

```
Build Error (Analyzer)

undefined: Duplicate declaration "Something"
   5 |
   6 | declare module 'my-app/something-2' {
>  7 |   import { Something } from 'somewhere';
     |            ^
   8 |   export default function something2(): Something;
   9 | }
  10 |
```

**Comment by csantero** [comment]
As a workaround, is there a way to configure ember-auto-import to ignore certain paths for analysis?

**Comment by ef4** [comment]
This is a `d.ts` file that's inside your ember app?

**Comment by csantero** [comment]
> This is a `d.ts` file that's inside your ember app?

@ef4 Yeah. Until I tried upgrading to ember-cli-typescript 2.0 it was never a problem before. I guess if I move it to `/types` that should let me avoid the problem?

**Comment by csantero** [comment]
Moving my .d.ts files to `/types` worked. Thanks

**Comment by ef4** [comment]
Yes, that is probably a good workaround.

I don't think this is an ember-auto-import issue. I just tested pasting your `d.ts` file into a new app with ember-cli-typescript (but not ember-auto-import) and it gets the same error.

Probably file a bug on ember-cli-typescript if d.ts files in app used to work but don't anymore.
