### ISSUE TITLE
How to use this with bootstrap4-toggle

### ISSUE THREAD

**Issue by Redsandro** [ef4/ember-auto-import#233]
I'm having an issue importing [`bootstrap4-toggle`](https://gitbrent.github.io/bootstrap4-toggle/).

The script doesn't seem to import, and the style is not available even though it does not complain about the style not being found. I've added the following tweaks:

`ember-cli-build.js`:

```js
'use strict'

const EmberApp = require('ember-cli/lib/broccoli/ember-app')

module.exports = function(defaults) {
	const app = new EmberApp(defaults, {
		'ember-bootstrap': {
			'bootstrapVersion': 4,
			'importBootstrapFont': false,
			'importBootstrapCSS': false
		},

		sassOptions: {
			includePaths: [
				'node_modules/bootstrap4-toggle/css'
			]
		},

		autoImport: {
			webpack: {
				externals: { jquery: 'jQuery' }
			}
		},
	})

	return app.toTree()
}
```

`app.scss`:

```
@import 'bootstrap4-toggle.min.css';
```

What am I missing here?

**Comment by ef4** [comment]
ember-auto-import doesn't have anything to do with importing CSS into SCSS. So whether or not that works is an issue for ember-cli-sass. 

As for the Javascript, that should be able to be auto-imported. But you need to put `import "bootstrap4-toggle"` somewhere in your own Javascript to make that happen.

**Comment by Redsandro** [comment]
I've moved on from this. I don't recall being so reckless as to forget to use `import`, but I probably was anyway.

Close for now.

#maintenance.
