### ISSUE TITLE
`skipBabel` is missing from the documentation

### ISSUE THREAD

**Issue by Turbo87** [ef4/ember-auto-import#234]
It seems that https://github.com/ef4/ember-auto-import/pull/225 introduced an option to opt-out of Babel transpilation for some dependencies, but it does not seem to be documented yet.

/cc @ef4 @pzuraq

**Comment by danwenzel** [comment]
@ef4 @pzuraq  - ping ⬆️

**Comment by ef4** [comment]
This is a good new contributor issue.

**Comment by danwenzel** [comment]
@ef4 @pzuraq - Sure, I might take a crack at this if I get an extra moment.

Can you explain what the `semverRange` option is? https://github.com/ef4/ember-auto-import/pull/225/files#diff-2738f4eb29dd8800a17168c3223e173bR10

**Comment by ef4** [comment]
Yeah, the idea is that you can say precisely what versions of the package should skip babel.

Given how NPM works, you can have many copies of the same library and they can be at different versions. This lets you get specific about which one is actually safe to use without going through babel.

**Comment by danwenzel** [comment]
Looks like this was done via https://github.com/ef4/ember-auto-import/pull/252
