### ISSUE TITLE
Can't resolve 'jnoty-inline' 

### ISSUE THREAD

**Issue by visualapps** [ef4/ember-auto-import#240]
👋 Hello, 

I am importing an npm package called "jnoty-inline:1.0.1" and getting Can't resolve 'jnoty-inline' build error. Can you help me to know what I'm missing here:

<img width="1676" alt="Screen Shot 2019-09-11 at 11 36 23 AM" src="https://user-images.githubusercontent.com/18216179/64672597-8a745a80-d489-11e9-877e-685dcc7d9e03.png">

<img width="792" alt="Screen Shot 2019-09-11 at 11 35 15 AM" src="https://user-images.githubusercontent.com/18216179/64672628-9d872a80-d489-11e9-8cc6-31cd6f545ec3.png">

<img width="796" alt="Screen Shot 2019-09-11 at 11 41 07 AM" src="https://user-images.githubusercontent.com/18216179/64672619-96601c80-d489-11e9-9d56-a8f2de19217b.png">

**Comment by ef4** [comment]
Hi. This appears to be a bug in jnoty-inline, not ember-auto-import.

The jnoty-inline package has an invalid `main` in its package.json. It points at a missing file. I would guess that it should change from `"main": "jnoty.js"` to `"main": "jnoty-inline.js"`. I tried this and the library loaded successfully under ember-auto-import.

**Comment by visualapps** [comment]
Thank you. @ef4 .
