### ISSUE TITLE
`Uncaught ReferenceError: a is not defined` with mapbox-gl in production mode

### ISSUE THREAD

**Issue by kasunvp** [ef4/ember-auto-import#251]
`a` in the error sometimes becomes `n`, I suppose due to dynamic naming at minification

Repo for reproduction: https://github.com/kasunvp/mapbox-gl-test (minimal app)

Error with `ember serve --prod` (can see the error even without the mapbox-gl access token)
Works with `ember serve` (have to add a mapbox-gl access token to load the map) 

The interesting fact is that we've been using ember-auto-import + mapbox-gl for some time now. Had a same kind of issue with a previous version, it was resolved and was working fine after using the ember-auto-import configuration `noParse: /(mapbox-gl)\.js$/` as was suggested somewhere. But not anymore with the latest versions.

Also, if the deprecated `ember-browserify` addon is used instead of ember-auto-import, it works fine too. So must be an issue in `ember-auto-import`/`webpack` combo.

Versions:
- Ember: v3.12.0
- ember-auto-import: v1.5.3
- mapbox-gl: v1.4.1

**Comment by ef4** [comment]
Thanks for sharing a working reproduction, I can confirm I see the bug.

**Comment by ef4** [comment]
Thanks for the update. Yes, skipBabel needs to get added to the readme, we have an open issue for that. I think it's a fine workaround to this problem. 

But I am still curious exactly what is breaking and I might dig in further. It's a little surprising that it breaks only in production, even after I remove uglify. That implies that either babel or webpack is doing something different in prod that results in invalid code.

**Comment by kasunvp** [comment]
That maybe because mapbox is using a separate dev package for the dev build and a transpiled one in prod.

Also I included PR for the README change. Please let me know how it looks :)
