### ISSUE TITLE
Unable to import dynamically in an addon

### ISSUE THREAD

**Issue by jrjohnson** [ef4/ember-auto-import#254]
I'm attempting to auto import from within an addon component. I created [this small example](https://github.com/jrjohnson/reporoduction-auto-import-dynamic-addon) which has the code:
```
didInsertElement() {
    import("highcharts").then(() => {
      this.set('done', true);
    })
  }
```
 Running in the dummy app I get `TypeError: error resolving module specifier 'highcharts'` which I believe means that the import wasn't transpiled. I have 
```
babel: {
  plugins: [ require.resolve('ember-auto-import/babel-plugin') ]
}
```
in the addons `ember-cli-build.js` file, but I wonder if there is something different I need to do from an addon to modify the babel plugins.

**Comment by jrjohnson** [comment]
There is something different to do. In an addon the configuration happens in `index.js` like
```
// index.js
module.exports = {
  options: {
    babel: {
      plugins: [ require.resolve('ember-auto-import/babel-plugin') ]
    }
  }
};
```

Documented in [ember-cli-babel](https://github.com/babel/ember-cli-babel#options).

**Comment by ef4** [comment]
Thanks for following up with the answer. We should probably put this in the README.

**Comment by jrjohnson** [comment]
Agreed. Added in #256.
