### ISSUE TITLE
String.prototype.pluralize() is deprecated. Please explicitly: import...

### ISSUE THREAD

**Issue by brunoocasali** [ef4/ember-auto-import#257]
First of all thanks for this library! 
And feel free to point me if this is not the right place to post this issue!

![image](https://user-images.githubusercontent.com/4116980/69204629-4014f700-0b26-11ea-854d-4b0868a49f16.png)

I just imported two new libraries to my test environment, and I started to get this deprecation messages, but I cant understand if is a auto-import issue or a `sinon` and `nise` issue...

Currently using `ember-source 3.14.1` and `ember-auto-import 1.5.3`

Can you help me with figuring out where this deprecation is coming from?

**Comment by ef4** [comment]
My guess is: for some reason Sinon is trying to copy `String.prototype`, which causes it to access `String.prototype.pluralize`, which triggers a deprecation message from Ember.

The only reason that deprecation is present is to support older code that relies on Ember to extend built-in prototypes like `String`. If you don't actually need that, you can turn it off by setting `EXTEND_PROTOTYPES: false` in `config/environment.js`. 

Alternatively, you can try to figure out why Sinon is copying `String.prototype`.

In any case, this is not an auto-import issue. If you're still stuck, file an issue on https://github.com/emberjs/ember-inflector. The deprecated code is already removed from master there, but unreleased, and I don't know why.
