### ISSUE TITLE
Cannot properly import pdfjs-dist

### ISSUE THREAD

**Issue by musaffa** [ef4/ember-auto-import#258]
`pdfjs-dist` is an official npm package of Mozilla's widely used [pdf.js](https://github.com/mozilla/pdf.js/) library. When trying to import this library with ember-auto-import, I get following import:

![Screenshot from 2019-12-07 01-01-15](https://user-images.githubusercontent.com/294616/70349027-1ed63980-188e-11ea-97c5-dbb4c5ef0367.png)

It's all default under default nested down! I also tried with an alternative ES6 ready [bundle](https://github.com/bundled-es-modules/pdfjs-dist) but I get almost the same result.

**Comment by ef4** [comment]
What you're seeing in the console doesn't mean the library isn't working right. This is a common compatibility pattern used by libraries that want to be consumed as both an ES module import and a CJS require. Their module is a value `m` where `m.default === m`. If you keep expanding `default` it goes on forever, but you're just looking at the same object over and over again.

Are you having trouble using the actual methods the library is supposed to provide?

**Comment by musaffa** [comment]
> Are you having trouble using the actual methods the library is supposed to provide?

Yes. I was trying to access `getDocument` method of pdfjs. But the only thing available is `default`. I also tried `pdfjs.default.getDocument` but no avail.

**Comment by ef4** [comment]
I made a [complete working example](https://github.com/ef4/demonstrate-pdfjs) showing how to use pdfjs-dist. I followed their [instructions for integrating with webpack](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#webpack).

The example app uses all Octane patterns. If you're not using Octane, you would do [this stuff](https://github.com/ef4/demonstrate-pdfjs/blob/d21ef897ea24a9fe92ab6e5f17a44d34529acccf/app/modifiers/render-pdf.js#L7) in a classic component's `didInsertElement` hook instead.

Notice there is a tiny bit of webpack config required [here](https://github.com/ef4/demonstrate-pdfjs/blob/d21ef897ea24a9fe92ab6e5f17a44d34529acccf/ember-cli-build.js#L8-L12) to make the web worker build.

**Comment by musaffa** [comment]
@ef4 Thank you so much. :fire:
