### ISSUE TITLE
Import dependencies that are related one to another

### ISSUE THREAD

**Issue by tehmaestro** [ef4/ember-auto-import#262]
Hi, I'm trying to use this plugin, but I'm having trouble understanding something. I use chartist and chartist-plugin-pointlabels.
 So I did:
```
npm install chartist
npm install chartist-plugin-pointlabels
```

Then, in a component
```
import Chartist from 'chartist';
import * as ChartistLabels from 'chartist-plugin-pointlabels';

//
let chart = new Chartist( ...
```

Is this the correct way? Chartist pointlabels is a plugin that attaches itself to `Chartist.plugins.pointLabels`, so I am essentially importing ChartistLabels just to let ember-auto-import know it should pull that dependency too. Is there a better way to do this? Maybe I can make sure that whenever I call `import Chartist from 'chartist'` , `pointlabels` is automatically loaded.

Also, chartist has a CSS file. Should I import this file as `app.import` in `ember-cli-build`? 
Thank you so much!

**Comment by ef4** [comment]
I looked over chartist's repo and all I can find is instructions for using plugins via a `Chartist` global variable. It's not clear if they support using them via module imports. You may need to do something like:

```js
import Chartist from 'chartist';
window.Chartist = Chartist;
import 'chartist-plugin-pointlabels';
```

In general you could ask the maintains "how do I use chartist plugins with webpack?" and those instructions will also apply to ember-auto-import.

> Also, chartist has a CSS file. Should I import this file as app.import in ember-cli-build?

This is planned and the underlying infrastructure is present but not implemented out of the box. At present you should `app.import('node_modules/chartist/whatever.css')` it in your ember-cli-build.js file.

**Comment by tehmaestro** [comment]
Thank you so much.
