### ISSUE TITLE
Updating to latest version causes build failure

### ISSUE THREAD

**Issue by BryanHunt** [ef4/ember-auto-import#263]
I'm trying to update to the latest version of ember-auto-import and I'm running into a build error.

I have an addon (nv-auth-login) that does `import jsonwebtoken` in the addon tree.  I have another addon that depends on the nv-auth-login addon and when I run the dummy app, I get:

```
ERROR in ../nv-auth-login/node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/bhunt/Development/Nvidia/libs/javascript/ember/nv-auth-login/node_modules/jwa'
 @ ../nv-auth-login/node_modules/jwa/index.js 5:13-30
 @ ../nv-auth-login/node_modules/jws/lib/sign-stream.js
 @ ../nv-auth-login/node_modules/jws/index.js
 @ ../nv-auth-login/node_modules/jsonwebtoken/decode.js
 @ ../nv-auth-login/node_modules/jsonwebtoken/index.js
 @ /private/var/folders/0p/35rj_jpx365f0plgs12ydxw40000gn/T/broccoli-32567pSG4VJqoxhGz/cache-399-bundler/staging/app.js
 @ multi /private/var/folders/0p/35rj_jpx365f0plgs12ydxw40000gn/T/broccoli-32567pSG4VJqoxhGz/cache-399-bundler/staging/l.js /private/var/folders/0p/35rj_jpx365f0plgs12ydxw40000gn/T/broccoli-32567pSG4VJqoxhGz/cache-399-bundler/staging/app.js
```

After some experimentation, I found that v1.3.0 is the latest version that works for me.

**Comment by ef4** [comment]
This is an FAQ, please see
https://github.com/ef4/ember-auto-import/blob/master/README.md#i-upgraded-my-ember-auto-import-version-and-now-things-dont-import-what-changed

**Comment by BryanHunt** [comment]
Thank you!  That fixed it.

**Comment by iamareebjamal** [comment]
Would be helpful if this is linked in the CHANGELOG file

**Comment by ef4** [comment]
Good idea, adding a link in the changelog.
