### ISSUE TITLE
Multiple sourcemappingURL entries in vendor.js

### ISSUE THREAD

**Issue by mwhitworth** [ef4/ember-auto-import#265]
See this repository for a [minimal reproduction](https://github.com/mwhitworth/ember-auto-import-repro/tree/sourcemapping-issues)

It seems like only one `sourceMappingURL` reference is supported - however, at the bottom of the built file, we have:

```
//# sourceMappingURL=chunk.bf5b8262abd99a072987.js.map//# sourceMappingURL=vendor.map
```

which has some issues:

- it's not a well-formed `sourceMappingURL` directive for `vendor.map`, given the text before it
- that other source map is not copied to the build output
- there are multiple `sourceMappingURL` directives, which don't seem to be widely supported.

Presumably we should merge the sourcemaps generated by `ember-auto-import` into `vendor.map` as part of the bundle generation?

**Comment by ef4** [comment]
Thank you for reporting.

This presumably broke back at https://github.com/ef4/ember-auto-import/pull/90

I wonder if ember-cli still has the bad circular broccoli dependency that forced that, maybe we can go back to emitting things more cleanly.

Alternatively, we could give up on merging into vendor.js entirely and keep our chunks separate. That will be cleaner and possibly faster. The one downside is that some people have very bespoke deployment pipelines that won't expect a new separate JS bundle.

**Comment by tmquinn** [comment]
Is there a work around for this? We recently added ember-auto-import to our app and now our sourcemaps are broken... :(

**Comment by mwhitworth** [comment]
> I wonder if ember-cli still has the bad circular broccoli dependency that forced that, maybe we can go back to emitting things more cleanly.

Unfortunately that circular dependency is still present, running with the latest `ember-cli` version. So building with e.g. `ember-auto-import` 1.2.5 and `ember-cli` :

> Cycle in node graph: BroccoliMergeTrees (Full Application) -> BroccoliMergeTrees (TreeMerger (ExternalTree)) -> Funnel (Packaged Vendor) -> BroccoliMergeTrees (TreeMerger (vendor)) -> BundlerPlugin -> Analyzer (ember-auto-import-analyzer) -> Funnel () -> BroccoliMergeTrees (TreeMerger (preprocessedApp & templates)) -> BroccoliMergeTrees (Full Application)

I'll investigate further, and see in `broccoli` / `ember-cli` how this change was introduced.

**Comment by rwjblue** [comment]
I believe this is fixed in ember-auto-import@2

**Comment by ef4** [comment]
Fixed in 2.0.

**Comment by davecombs** [comment]
Can you tell me then how our LI vendor.js file contains multiple sourceMappingURL entries (even with the EAI 2.0 upgrade) and works? Shouldn't that fail?

**Comment by ef4** [comment]
@davecombs if your app has ember-auto-import 2.0, then ember-auto-import doesn't put anything in vendor.js at all, so maybe they are coming from something else.
