### ISSUE TITLE
Possibly not compatible with ember-cli-typescript@alpha.1?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/ember-auto-import#267]
Getting these errors:
```
Error: Could not find module `qrcode` imported from `emberclear/utils/string-encoding`
Error: Could not find module `showdown` imported from `emberclear/utils/dom/utils`
Error: Could not find module `testdouble` imported from `emberclear/tests/unit/service/notifications-test`

# and a bunch of: 
TypeError: Cannot read property 'exports' of undefined
```

The only change is going from 
```
-    "ember-cli-typescript": "^3.1.3",
+    "ember-cli-typescript": "^4.0.0-alpha.1",
```

Not sure how ec-typescript is related to these behaviors, but the modules missing are auto-imported.

And I'm very unsure about the Cannot read property exports of undefined error.
![image](https://user-images.githubusercontent.com/199018/73967028-22655b80-48e5-11ea-9484-a7cf9bd82f83.png)

I think I need to debug the node build process to get further information, cause this is all I have atm:
![image](https://user-images.githubusercontent.com/199018/73967092-3e68fd00-48e5-11ea-8c8d-f25d9c8db8ba.png)

Two commits here:
 - https://github.com/NullVoxPopuli/emberclear/pull/488/commits

first has green tests
second has all the module load errors (after upgrading ember-cli-typescript)

**Comment by dfreeman** [comment]
@NullVoxPopuli can you confirm that your app works with the latest `ember-cli-babel` _without_ upgrading `ember-cli-typescript`? The only meaningful change from 3.x to the new 4.0 alpha is that the responsibility for adding `@babel/plugin-transform-typescript` moved from `ember-cli-typescript` to `ember-cli-babel`, which I wouldn't expect to have any impact here (though I could be wrong!)

**Comment by NullVoxPopuli** [comment]
> can you confirm that your app works with the latest ember-cli-babel without upgrading ember-cli-typescript? 

yeah, these two commits show this: 
![image](https://user-images.githubusercontent.com/199018/73976680-d3c0bd00-48f6-11ea-90a8-26c8c7d2a956.png) (ignore the red x's, those don't matter here (though, if you click on them, you'll see that tests pass for first, but don't for the second))

I mean, your description of what ec-typescript is doing sounds simple!
I'm only debugging this in spurts, so.. idk. As I'm casually I'm debugging (with the alpha): 
![image](https://user-images.githubusercontent.com/199018/73977157-cf48d400-48f7-11ea-866b-f457dbee71d3.png)
(from requirejs, I think)

![image](https://user-images.githubusercontent.com/199018/73977239-fdc6af00-48f7-11ea-93b2-d20ad73b088a.png)

**Comment by nightire** [comment]
Yes, I found this issue too.

I'm using `ember-cli-typescript@4.0.0-alpha.1` with `ember-auto-import@1.5.3`. If using ember-auto-import in a `.ts` file, required modules are always missing, no matter been imported statically or dynamically. However, if I change this file to `.js` extension, required modules are loaded correctly.

I tried `DEBUG=ember-auto-import:*` to compare the difference, and I found ember-auto-import didn't analyze any `.ts` files.

**Comment by dfreeman** [comment]
It looks like the problem is here:
https://github.com/ef4/ember-auto-import/blob/a9f41b1e989e4e5af16714ba819ded79995dea65/packages/ember-auto-import/ts/package.ts#L60-L61

`ember-cli-babel` now assumes it should transpile `.ts` files by default either if `ember-cli-typescript>=4.0.0-alpha.1` is present, or if the `enableTypeScriptTransform` flag is set in its options:

https://github.com/babel/ember-cli-babel/blob/bc32a8ca546c30eb5ee1e231d81c67688a29bb7b/index.js#L337-L346

**Comment by nightire** [comment]
Yeah, I tested it with embroider and it works well, so it's not the problem of `ember-cli-typescript@4.0.0-alpha.1`

**Comment by NullVoxPopuli** [comment]
I have this problem with embroider as well, I think -- still investigating

**Comment by lifeart** [comment]
I confirm same issue with ember-cli-typescript 4.1 & ember-cli-babel "7.24.0

**Comment by lifeart** [comment]
@dfreeman fix helps me 

```
diff --git a/node_modules/ember-auto-import/js/package.js b/node_modules/ember-auto-import/js/package.js
index 40b93f8..6e9ac22 100644
--- a/node_modules/ember-auto-import/js/package.js
+++ b/node_modules/ember-auto-import/js/package.js
@@ -77,7 +77,7 @@ class Package {
         // match.
         let babelAddon = instance.addons.find(addon => addon.name === 'ember-cli-babel');
         let babelOptions = babelAddon.buildBabelOptions(options);
-        let extensions = babelOptions.filterExtensions || ['js'];
+        let extensions = babelOptions.filterExtensions || ['js','ts'];
         // https://github.com/babel/ember-cli-babel/issues/227
         delete babelOptions.annotation;
         delete babelOptions.throwUnlessParallelizable;

```

**Comment by lifeart** [comment]
@dfreeman , @ef4 wondering, could we just check for ember-cli-typescript and if it's installed and >=4, then manually add `ts` to extensions list to solve it?
