### ISSUE TITLE
Issue importing lodash not lodash-es

### ISSUE THREAD

**Issue by LiquidSean** [ef4/ember-auto-import#27]
Error is - Global error: Uncaught Error: Could not find module `lodash` imported from

I am importing lodash as ` import _ from 'lodash' ` unsure if I need additional configuration in my addons index.js file. Other imports appear to be working fine with ember-auto-import.

**Comment by ef4** [comment]
Thanks. I just tested this using v0.2.3 and it worked, please reopen if you can still reproduce the bug.
