### ISSUE TITLE
`AutoImport.lookup(appOrAddon)` doesn't support multi-project builds

### ISSUE THREAD

**Issue by buschtoens** [ef4/ember-auto-import#278]
`AutoImport.lookup(appOrAddon)` doesn't support building multiple projects in the same process, registering on `global` assumes that you'll only have one [`Project`](https://ember-cli.com/api/classes/Project.html) instance per Node process.

https://github.com/ef4/ember-auto-import/blob/74dcdf289bdb03542f345a1ad8f660558fdc61be/packages/ember-auto-import/ts/auto-import.ts#L22-L28

In my case I am pre-rendering a little dummy app via `ember-cli-fastboot` and inject the output HTML into the host app's `index.html` at build time.

The dummy app fails to render, if it tries to import anything via `ember-auto-import` as the imports are registered at the host app instead.

**Comment by buschtoens** [comment]
I'll try to submit a fix, by including a the root `EmberApp` / `EmberAddon` or `Project` into the key.

**Comment by ef4** [comment]
Makes sense. 👍

**Comment by buschtoens** [comment]
Was there a specific reason to register the singleton on `global` instead of the consuming `EmberApp` instance?

How about something like:

```ts
 static lookup(appOrAddon: any): AutoImport { 
   let app = appOrAddon.app ?? appOrAddon; 
   if (!app[protocol]) { 
     app[protocol] = new this(appOrAddon); 
   } 
   return app[protocol]; 
 } 
```
