### ISSUE TITLE
microstates not importing from modules

### ISSUE THREAD

**Issue by taras** [ef4/ember-auto-import#28]
I just changed `ember-microstates` to use `ember-auto-import@0.2.2` but its not registering the import. I'm getting `Could not find module `microstates` imported from `ember-microstates/service`. 

<img width="950" alt="screen shot 2018-06-18 at 6 30 35 pm" src="https://user-images.githubusercontent.com/74687/41567427-c42c721a-7325-11e8-93c5-1d745edaee29.png">

Here is the branch https://github.com/knownasilya/ember-microstates/blob/07470799b612c3dd8db9c2472d2dfe4ab0caf324/package.json#L28 

Any idea why this might be happening?

**Comment by ef4** [comment]
Thanks, your reproduction commit let me find the problem. Depending on the exact set up addons involved and the order they loaded in, sometimes we were running the import analysis after babel had already transpiled away the imports.

**Comment by ef4** [comment]
Fixed in 96ae2c3449d46089f6d9a9e630eb6c33bb07cb23

**Comment by taras** [comment]
Thank you!
