### ISSUE TITLE
Imported module is bundled into vendor.js instead of test-support.js

### ISSUE THREAD

**Issue by simonihmig** [ef4/ember-auto-import#284]
It seem under a certain condition it is possible that an imported module is put into `vendor.js` in instead of `test-support.js`, making it get shipped to users. 😟

This happens when:
* the addon has an `treeForAddonTestSupport` hook that removes the `/test-support` module namespace, by not calling `_super`. Which a lot of addons that are focused on testing only do, e.g.  https://github.com/emberjs/ember-qunit/blob/master/index.js#L78-L81
* in the `/addon-test-support` tree there is an import statement for a npm package handled by `ember-auto-import`

The concrete case where I witnessed this is for `ember-cli-yadda`, where the above conditions are fulfilled:
* https://github.com/albertjan/ember-cli-yadda/blob/master/index.js#L48
* https://github.com/albertjan/ember-cli-yadda/blob/master/addon-test-support/index.js

When I remove the overridden `treeForAddonTestSupport`, the `yadda` library is added to `test-support.js`. And when I remove the [import](https://github.com/albertjan/ember-cli-yadda/blob/master/addon-test-support/index.js) then obviously `yadda` is not imported ata ll (ensuring this was the offending `import` that caused the incorrect bundling)

No idea if this is easy or hard to fix? For the current case I believe we can workaround this pretty well. But still think this looks like a bug here.

**Comment by ef4** [comment]
Thanks for reporting Simon. The code that controls this is in
bundle-config.ts. There’s a regexp that looks for test-support. That
strategy probably fails in this case.

It would be better if we could tell which tree we were preprocessing, but I
don’t know if preprocessor are given that info. One place to poke around is
if our toTree method has access to any additional info we could capture.

**Comment by simonihmig** [comment]
I poked around a bit in node debugger, but there seems to be nothing reliable we can use here. At some early point in the call stack the addon is called with `addon.treeFor(type)` (with `type` being `"addon-test-support"` here), but that info is lost from then on...

Adding that kind of meta data to the trees would be some pretty invasive change I think, requiring updates to `ember-cli` itself. Also probably a controversial change...

What we could do quite easily I think is to add some meta data to the options passed to `preprocessJs()` here: https://github.com/albertjan/ember-cli-yadda/blob/master/index.js#L64. Something like:

```js
return this.preprocessJs(namespacedTree, '/', this.name, {
  registry: this.registry,
  autoImport: {
    bundleType: 'test'
  }
});
```

This options hash would get passed up to the `toTree()` method already, so we could pass that along to the analyzer and let that overrule the current regex-based heuristics.

This would hover require any addons to play nicely, i.e. pass that information. But as that would be needed only in the case the `treeForAddonTestSupport` hook is overridden, *and* that requires also to explicitly call `preprocessJs()` anyway, *and* making sure `ember-auto-import` works is a concern of the addon already (as it has it as its dependency), that would seem ok for me.

What do you think?

**Comment by paddyobrien** [comment]
I've run into a similar problem with packages being bundled into vendor from addon-test-support. I notice that the regexp used to detect test-support won't work with scoped package imports. 

Would a change like this make sense? https://github.com/paddyobrien/ember-auto-import/commit/d21311036debebba5a4fd5ff969cab86ebe6b578

**Comment by rwjblue** [comment]
Oh no! Looks like the strategy that we moved to with `ember-qunit@5` is going to suffer from this bug severely. 😩 

At the moment, `ember-qunit@5.1.0` requires folks to consume `qunit` via `ember-auto-import` which puts it into `vendor.js` by default.

**Comment by ef4** [comment]
I don’t see a clean automatic solution to this problem. ember-cli doesn’t tell us what kind of tree we are analyzing, and looking at the module naming alone is not reliable. 

I guess we can require addons to configure this. So ember-qunit would explicitly tell ember-auto-import “the following modules of mine are for test-support”.
