### ISSUE TITLE
Component with ember-concurrency-decorators gives "Ignoring an unparseable file" error

### ISSUE THREAD

**Issue by AndreJoaquim** [ef4/ember-auto-import#286]
Hello! 👋 

Today I've faced an awkward issue where I had a dynamic import in a native class component that has an `ember-concurrency` task defined with `ember-concurrency-decorators`. The component's code the following:

```js
import Component from '@ember/component';
import { timeout } from 'ember-concurrency';
import { task } from 'ember-concurrency-decorators';

export default class Select extends Component {
    async getSlug(name) {
        const { default: slug } = await import('slug');

        return slug(name, { lower: true, replacement: ' ' });
    }

    @task({ restartable: true })
    *search(term) {
        yield timeout(300);

        try {
            const slug = yield this.getSlug(term);
            const results = yield fetch(...).then((res) => res.json())

            return results;
        } catch (e) {
            console.log(e);
        }
    }
}
```

In the template, I call the task using `{{perform this.search}}`. At first, the error was that the dynamic module couldn't be found, so I started digging deeper. I tried importing this same module dynamically in a separate component, and it worked. Therefore, I excluded it was the package's issue (in this case, `slug`).

As I booted up the server with `ember-auto-import`'s debug on, I found no imports where found in this component, and I found the following error message:

```bash
  ember-auto-import:analyzer updating imports for my-app/pods/components/select/component.js, 2545 +27s
  ember-auto-import:analyzer Ignoring an unparseable file +10ms
```

After I've removed the `task`, everything run smoothly and the dynamic imports where found... I'm not even sure what the issue is, but I'd like to not switch to the classic component 😅 

Thanks in advance! 👍

**Comment by ef4** [comment]
It sounds like the version of `@babel/core` that's being used by ember-auto-import isn't new enough to parse some syntax here. Try letting it update (as opposed to keeping it locked with yarn.lock or package-lockk.json).

**Comment by AndreJoaquim** [comment]
@ef4 During this week I'll try letting it update and let you know how did it go. Thanks for the help!

**Comment by AndreJoaquim** [comment]
@ef4 I've actually just tried it right now and updating `@babel/core` to `7.10.2` fixed the issue 😄 Thanks for the help :)
