### ISSUE TITLE
Will this handle all the types of transforms that can be done in ember-cli-build?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/ember-auto-import#3]
for example, I currently have these:

```js
  app.import('node_modules/phoenix/assets/js/phoenix.js', {
    using: [{ transformation: 'cjs', as: 'phoenix' }],
  });

  // libsodium
  app.import('node_modules/libsodium/dist/modules/libsodium.js');
  app.import('node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js');
  app.import('vendor/shims/libsodium.js');
  app.import('vendor/shims/libsodium-wrappers.js');

  // qrcode
  app.import('node_modules/qrcode/build/qrcode.min.js');
  app.import('vendor/shims/qrcode.js');

  // localforage
  app.import('node_modules/localforage/dist/localforage.js');
  app.import('vendor/shims/localforage.js');

  // uuid
  app.import('node_modules/uuid/index.js', {
    using: [{ transformation: 'cjs', as: 'uuid' }]
  });
```

with `ember-auto-import`, would I just delete all that and then also delete all my vendor/shims?
(I assume I would for the non-configured imports, but am mostly asking about cjs, u/amd, etc)

great work on this library!

**Comment by ef4** [comment]
That is definitely the goal. We will probably find some edge cases, so please report bugs. But I don't see any reason to expect that all of the ones you listed shouldn't just work.

**Comment by ef4** [comment]
We will probably want to add some optional configuration that lets people customize rollup plugins, etc, for cases where a library needs special handling.

**Comment by NullVoxPopuli** [comment]
Cool, I'll give it a go
