### ISSUE TITLE
Chunk file missing /assets prefix

### ISSUE THREAD

**Issue by adambedford** [ef4/ember-auto-import#314]
I'm running into an issue where a chunk file can't be loaded because it's looking for it at `localhost:4200/chunk.js` (I've excluded the fingerprint for simplicity) rather than `localhost:4200/assets/chunk.js`.

We're using `ember-auto-import` version `^1.6.0`. Here's the import code:

```javascript
const module = await import('@ckeditor/ckeditor5-build-classic')
const ClassicEditor = module.default
```

Any guidance would be greatly appreciated!

**Comment by ef4** [comment]
Questions that could help:

 - Are you using `defer` on your script tags in index.html?

 - Are you customizing ember-auto-import's `publicAssetURL` setting?

 - Are you using `fingerprint: { prepend: '...' }` in ember-cli-build.js?

The way this is supposed to work is, if you explicitly set a `publicAssetURL`, that is where lazy chunks will load from. If you don't set one, we try to load them from the same place as the currently executing chunk, but that only works if the chunk has been executed synchronously.

**Comment by adambedford** [comment]
Hi @ef4 ,

Thanks for your questions...

* Yes, using `defer` on both `vendor.js` and `frontend.js`
* No, not customising `publicAssetURL`
* Yes, prepending a cloudfront URL

I can confirm that setting `publicAssetURL` to `/assets` fixes this and I now realise I completely overlooked that in the Readme :facepalm:

Thanks for the guidance!
