### ISSUE TITLE
Sourcemaps for dynamically imported chunks

### ISSUE THREAD

**Issue by miguelcobain** [ef4/ember-auto-import#316]
Is there a way to instruct ember-auto-import or webpack to generate source maps for dynamically imported chunks?

Perhaps ember-auto-import could default such an option to the project's `sourcemaps: { enabled: true }` option.

**Comment by simonihmig** [comment]
You can set a [webpack devtool](https://webpack.js.org/configuration/devtool/) option, like:

```
    autoImport: {
      webpack: {
        devtool: 'source-map',
      },
    },
```

**Comment by ef4** [comment]
That is correct. 

We stick to the webpack defaults for this, which don't use `"source-map"` in development because it's a little bit slower than the default of `"eval"`.
