### ISSUE TITLE
Snyk - Vulnerability Issue

### ISSUE THREAD

**Issue by karthiksubbiah1983** [ef4/ember-auto-import#318]
We are using ember-cognito for our project, which has dependency on ember auto import. Snyk has identified vulnerability in one of the dependency used. 

Introduced by ember-cognito@0.10.0 > **ember-auto-import@1.7.0** > webpack@4.44.2 > terser-webpack-plugin@1.4.5 > cacache@12.0.4 > y18n@4.0.0. 

Please provide an updated version of ember auto import with updated webpack.

**Comment by ef4** [comment]
Snyk is wasting your time by treating build-time code as if it was run-time code. This vulnerability is not relevant.

There is no way to pass untrusted input through ember-auto-import, because by definition it only looks at **your code**, which can always do anything it wants.

**Comment by ef4** [comment]
But also, ember-auto-import uses a caret dependency on webpack, so you should be able to upgrade it without any changes in ember-auto-import.
