### ISSUE TITLE
No 1.7.0 release tag in the repo

### ISSUE THREAD

**Issue by patocallaghan** [ef4/ember-auto-import#320]
It appears that the last release was tagged with [1.17.0](https://github.com/ef4/ember-auto-import/releases/tag/v1.17.0) instead of 1.7.0

![image](https://user-images.githubusercontent.com/685034/100641088-f234f080-332e-11eb-9250-abe89cca524c.png)

**Comment by ef4** [comment]
Oops, thanks, this is fixed now.
