### ISSUE TITLE
Webpack 5 support?

### ISSUE THREAD

**Issue by patocallaghan** [ef4/ember-auto-import#321]
Webpack 5 was released ~1.5 months back ([release post](https://webpack.js.org/blog/2020-10-10-webpack-5-release/)) with a lot of new features. Have you had any thoughts on upgrading the webpack dependency to v5?

I'm quite curious about the new [persistent caching feature](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#persistent-caching) and I attempted a spike over [here](https://github.com/ef4/ember-auto-import/compare/master...patocallaghan:patoc/webpack-5) (i.e. did the bare minimum to make it compile) and try it out in our quite large app through `yarn link`. I configured it to use the persistent caching settings in the `autoImport.webpack` config in ember-cli-build.js, and I see a consistent 10-15 second speed boost on warm build startups as the `Bundler` step is reduced to just a few seconds with a primed cache.

Here's an extremely [simplified app](https://github.com/patocallaghan/deps-app) with [a few deps](https://github.com/patocallaghan/deps-app/blob/d2b75c399e445a4ef74180e1e5baa660487f01dc/app/controllers/application.js#L2-L20) and the [persistent caching config](https://github.com/patocallaghan/deps-app/blob/d2b75c399e445a4ef74180e1e5baa660487f01dc/ember-cli-build.js#L8-L14). As you can see there's a 5 second boost to the warm build startup time, and this is a tiny app.

### Webpack 4
![image](https://user-images.githubusercontent.com/685034/100671036-b4988d80-3357-11eb-8bad-5b154d016714.png)

### Webpack 5 + persistent cache
![image](https://user-images.githubusercontent.com/685034/100671082-c712c700-3357-11eb-970b-18a5d4b7b34b.png)

I guess there would be some things to consider:
1. There doesn't appear to be any breaking changes with regards the [configuration options ember-auto-import uses](https://webpack.js.org/migrate/5/#update-outdated-options) in the [internal webpack config](https://github.com/ef4/ember-auto-import/blob/7610021b3c592bcaa5a649a1d6fa799826f857d3/packages/ember-auto-import/ts/webpack.ts#L90-L121)
2. While webpack is an internal dependency, consuming apps may configure webpack themselves using the `autoImport.webpack` config so this would be a breaking change for them
3. Should the persistent cache functionality be configured as part of ember-auto-import's internal webpack config to allow others to benefit from it out of the box. Should it be left to the consumer? Webpack doesn't enable this feature by default due to the [various cache invalidation strategies](https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md) you could possibly want. If we were to include this we'd probably have to figure out which cache busting strategy to use.

**Comment by patocallaghan** [comment]
Just to follow up on some of the persistent cache questions in my issue description. I've confirmed that the cache is adequately invalidated in various scenarios when I used the following configuration:

```js
autoImport: {
  webpack: {
    cache: {
      type: 'filesystem',
        buildDependencies: {
          config: [__filename]
        }
      },
    }
  }
}
```

| test case | webpack 4 | webpack 5 + caching |
|-|-|-|
| Dependency not used - _not in output_ | ✅ | ✅ |
| Add import to code - _in output_ (reload + restart) | ✅  | ✅ |
|Remove import to code - _not in output_ (reload + restart) | ✅  | ✅ |
|Update dependency package version - _in output_ (restart)| ✅ | ✅ |
|No change - _caching works_ (restart) | ❌  | ✅ |

**Comment by ef4** [comment]
Yes, we should definitely plan to upgrade to webpack 5.

I'm fine with turning on persistent caching by default as long as we can manage settings that are safe for ember apps. Since ember-cli already does persistent caching, if we adhere to similar semantics I think it will be good.

**Comment by ef4** [comment]
As for a breaking major release, yes, I agree this should probably cause ember-auto-import 2.0. However, due to the "only one wins" policy we use, this means addons don't have control over when they get the major bump -- if the app picks a newer major, the addons will get built under that version. At a minimum, we should make sure we generate a good error message if an addon tries to use a webpack 4 feature when we're on webpack 5.

**Comment by gabrielcsapo** [comment]
I took a try at updating to v5 and getting it to run in our addon and apps without a problem https://github.com/ef4/ember-auto-import/pull/327

**Comment by patocallaghan** [comment]
Thanks @gabrielcsapo and @ef4 for getting this closed 🎉
