### ISSUE TITLE
i'm getting spread operators in IE 11

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [ef4/ember-auto-import#335]
I have an ember app build with "ie 11" in target

and I'm getting in my vendor.js :

```
  window.emberAutoImportDynamic = function(specifier, ...args) {
    if (args.length === 0) {
      return r('_eai_dyn_' + specifier);
    } else {
      return r('_eai_dynt_' + specifier)(...args)
    }
  };
```

which makes an script1010 expected identifier error due to the spread operator : ...args

Short version : the app is now completely broken on IE 11.

any idea why ?

I checked on babel, and it does get transpiled to ES5 if I pick "ie 11" as profile

**Comment by ef4** [comment]
This looks like a regression introduced in https://github.com/ef4/ember-auto-import/commit/032a1025fd9caa578f4da15c218b0c10ad699872 last week. We'll need to do a quick patch release.

I don't know why that particular generated file isn't going through babel-preset-env, but before it didn't use any features that needed transpilation so we didn't notice, and now it does.

**Comment by ef4** [comment]
Sorry about that, this is fixed in release 1.10.1.

**Comment by ef4** [comment]
For reference, I do remember now why that files doesn't go through babel, and it probably needs to stay that way, so it needs to be authored without any unsafe features.

**Comment by AdrienNguyenWorldline** [comment]
Rebuilding with 1.10.1 dit fix the issue.
