### ISSUE TITLE
Add power user mode where you don't scan

### ISSUE THREAD

**Issue by kellyselden** [ef4/ember-auto-import#35]
It would be nice to use the bulk of this addon to just shim for you, not detect. Your config could look like:

```js
  autoImport: {
    parsingDisabled: true,
    include: ['some-package'],
    webpack: {
      // extra webpack configuration goes here
    }
  }
```

This will be useful for people that already have really slow builds, but want the simplicity of this addon.

**Comment by ef4** [comment]
Interesting, this could indeed be made to work, and it would even scope correctly such that if _another_ addon in your build still wants parsing it can still have it.

This would probably be nice even just for making performance comparisons so we can understand more precisely how much we're paying to parse each package that uses ember-auto-import.

**Comment by ef4** [comment]
The `include` bit would probably need to act more like the real analyzer output, which is more like:

```
autoImport: {
    parsingDisabled: true,
    include: {
      'some-package' : ['app/components/foo.js']
    },
    webpack: {
      // extra webpack configuration goes here
    }
  }
```

This is how we can tell whether the included module needs to be used from app code vs test code, and the splitting logic is generalized so that in the future people could split into more bundles too. You could get away with not having _exactly_ the right set of paths in your config, as long as it results in putting your module into the right bundles.

**Comment by ef4** [comment]
Possibly we can just allow a custom parser, which would let you cheat:

```js
function hardCodedImports({ app, tests }) {
   return async function(relativePath, getSource) {
     if (relativePath === 'app/app.js') {
       return app;
     }
     if (relativePath === 'tests/test-helper.js') {
       return tests;
     }
   }
}
```

```js
autoImport: {
    parseImports: hardCodedImports({
      app: ['moment'],
      tests: ['some-test-helper']
    })
  }
```

**Comment by ef4** [comment]
After thinking about it, I would rather support this by splitting out a common library that could be shared by another addon that works as described. It would not be "auto" import, it's a different thing.
