### ISSUE TITLE
Lazy loaded chunks and Google Tag Manager

### ISSUE THREAD

**Issue by BarryThePenguin** [ef4/ember-auto-import#352]
We recently started using dynamic imports with `ember-auto-import` to load [`Intl` polyfills](https://formatjs.io/docs/polyfills) for [`ember-intl`](https://ember-intl.github.io/ember-intl/docs/runtime-requirements)

It appeared to work great during development. It also looked good when the changes went live. Then we started to receive queries from customer support about the app being down 😭 

We tracked the issue down to Google Tag Manager inserting script tags between the `vendor.js` and `app.js` files.. A slower internet connection, and a large uncached `vendor.js` file also exacerbates the issue.

I saw an assumption in `webpack.ts` that `app.js` needs to be the last script tag loaded in the DOM.

https://github.com/ef4/ember-auto-import/blob/36ec50390dfd75418d80731b2944f1660f0fee02/packages/ember-auto-import/ts/webpack.ts#L20-L36

Is there a way to guarantee this will happen? Particularly where GTM is involved? Has anyone else run into a similar issue?

Our script order currently looks something like..

```html
<script async src="//www.googletagmanager.com/gtm.js?id=GTM-XYZ"></script>
<script src="/assets/vendor.js"></script>
<script src="/assets/app.js"></script>
```

If `vendor.js` takes a long time to load/parse/run, GTM can start inserting additional script tags at the end of them DOM

```html
<script async src="//www.googletagmanager.com/gtm.js?id=GTM-XYZ"></script>
<script src="/assets/vendor.js"></script>
<script async src="//www.some-hot-analytics.com"></script>
<script>
  window.more_analytics = 'custom html';
</script>
<!-- The app.js script tag hasn't even been parsed yet -->
```

Even once `app.js` has been loaded and parsed, there could be even more script tags inserted after it..

```html
<script async src="//www.googletagmanager.com/gtm.js?id=GTM-XYZ"></script>
<script src="/assets/vendor.js"></script>
<script async src="//www.some-hot-analytics.com"></script>
<script>
  window.more_analytics = 'custom html';
</script>
<script src="/assets/app.js"></script>
<script async src="//www.gotta-catch.em/all.js"></script>
```

Then we see the app failing to load scripts from `https://www.gotta-catch.em/chunk.1.efghijk.js`

We could use `publicAssetURL`, but that appears to be a static value that gets set at build time? We deploy our ember app to multiple asset hosts, and dynamically change our asset host at run time.. This is something I'd like to change, but I don't see us changing it any time soon...

**Comment by ef4** [comment]
>  but that appears to be a static value that gets set at build time? We deploy our ember app to multiple asset hosts, and dynamically change our asset host at run time.

It's true that ember-auto-import consumes `publicAssetURL` at build time. But the underlying webpack feature that it's configuring can be set at runtime: you can set the global variable `__webpack_public_path__`.

**Comment by BarryThePenguin** [comment]
We have ended up using https://github.com/adopted-ember-addons/ember-metrics to load the GTM script tag, _after_ the ember app is initialised.

This allows us to avoid GTM injecting tags while the browser is still downloading and parsing the rest of the initial page load.

Still feels a bit precarious as it requires things to be loaded and called in a specific order..

I'd like to see us make use of `publicAssetURL` or `__webpack_public_path__`, but it's not really feasible with out current deployment process..
