### ISSUE TITLE
Dependencies in `.ts` files not included with latest `ember-cli-babel`

### ISSUE THREAD

**Issue by dfreeman** [ef4/ember-auto-import#359]
It looks like `ember-cli-babel@7.24.0` [dropped several items it previously returned](https://github.com/babel/ember-cli-babel/commit/5eafd6baad763786246e06f862704a770be6ffc9#diff-4d3a8edb07aff5a7c43d8692de88a4eb83b327e2a352633699ba4afb9b753b6aL39-L51) from `getBabelOptions()`, including the `filterExtensions` array that `auto-import` was relying on to determine whether to analyze `.ts` files.

It seems like we either need to duplicate `ember-cli-babel`'s "should we process TypeScript" logic here, or (I think preferably) `ember-cli-babel` should expose an explicit way to retrieve its configured file extensions.

I think this is likely the cause of the recently added comments on https://github.com/ef4/ember-auto-import/issues/267

**Comment by wagenet** [comment]
Also seeing this.

**Comment by rwjblue** [comment]
just released https://github.com/babel/ember-cli-babel/releases/tag/v7.26.1 which should mitigate
