### ISSUE TITLE
Dependencies are not properly transpiled with expected babel options/plugins

### ISSUE THREAD

**Issue by bjornharrtell** [ef4/ember-auto-import#371]
An example is if you have an npm package that has code that requires @babel/plugin-proposal-class-properties it will fail on build claiming it is not added to plugin section of options.

I can reproduce this in a plain new ember-cli new project, adding and using a simple example package like this one:
https://github.com/bjornharrtell/class-prop-js, that will fail with something like:

```
ERROR in ./node_modules/class-prop-js/test.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/bjorn/code/use-class-prop-js/node_modules/class-prop-js/test.js: Support for the experimental syntax 'classProperties' isn't currently enabled (2:10):

  1 | class Test {
> 2 |     test = null
    |          ^
  3 | }

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.
```

**Comment by bjornharrtell** [comment]
Perhaps worth noting that this could be worked around by adding a babel.config.json to the ember project root that added the needed config, but that is not possible after https://github.com/ef4/ember-auto-import/pull/360 and is probably not a good workaround anyway.

**Comment by ef4** [comment]
This is by design. We only apply some standard transformations (like preset-env) to third-party code.

You can add your own babel-loader directly to your webpack config if there's something in particular you need to rewrite. It's best to have relatively specific module rules so that you're only transpiling the package that needs it.

**Comment by bjornharrtell** [comment]
I see. Tried the following and getting it to build but with "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted". When run it seems it haven't been able to bundle a transitive dependency on `js-yaml`. Strange this "just works" if I with resolutions force `ember-auto-import` to 1.10.1.

```json
autoImport: {
      webpack: {
        plugins: [new webpack.IgnorePlugin(/vm/)],
        module: {
          rules: [
            {
              test: /\.m?js$/,
              use: {
                loader: 'babel-loader',
                options: {
                  presets: ['@babel/preset-env'],
                  plugins: ['@babel/plugin-proposal-class-properties', '@babel/plugin-syntax-dynamic-import']
                }
              }
            }
          ]
        }
      }
    }
```

**Comment by bjornharrtell** [comment]
I got it to work by making the test property more selective and tweaking the plugins settings to match exactly the dependent problematic package.
