### ISSUE TITLE
Could not find module, from fresh addon named with the format of `@prefix/suffix`

### ISSUE THREAD

**Issue by bestdoggo** [ef4/ember-auto-import#373]
Ember version `3.25.1` (though I also tried going back to `3.22.0`, no difference)

It's a fairly common pattern for npm packages to be namespaced like `@foo/bar` where **foo** is the company or org, and **bar** is the addon.

```bash
ember addon @foo/bar
cd foo-bar
npm i lodash-es --save-dev
```

Then we can do `import { capitalize } from 'lodash-es';` in `tests/dummy/app/app.js` and it **works just fine**.

_However_, if we do the same import in a new component...

```bash
ember g component example
ember g component-class example
```
Adding `import { capitalize } from 'lodash-es';` in `addon/components/example.js` will throw a `Could not find module` error for `lodash-es`. This is true regardless of if we run tests, or try to include `<Example />` in the dummy `application.hbs`.

**Comment by ef4** [comment]
Did you put `lodash-es` in `dependencies` or `devDependencies`? Because only `dependencies` are available from within addon code.

**Comment by bestdoggo** [comment]
@ef4 I have tried it in both locations, same result.

Still debugging things and trying to get to the bottom of it.

**Comment by bestdoggo** [comment]
Hmm I may close this until I have a better debug... I just reproduced this locally with a completely different repro.

```bash
ember addon foo
cd foo
npm i --save-dev lodash-es
ember g component bar
ember g component-class bar
```
Then trying to import `lodash-es` from the `app.js` works but not from a component rendered on the dummy page. Perhaps it's something on my system messing up, tbd... I'll debug locally for now. Sorry for the trouble~!
