### ISSUE TITLE
auto-imported library source code appears multiple times in production vendor.js

### ISSUE THREAD

**Issue by tomwayson** [ef4/ember-auto-import#378]
We have `import autocomplete from 'autcomplete.js'` in four files. Each file is in a different package w/in our monorepo. One is a component in the top level application. Another is a component in a low level addon. The third is a service in another addon. The fourth file is a component in a lazily-loaded engine. When I do a production build, I see the signature of the autocomplete.js source code in vendor.js three times:

![image](https://user-images.githubusercontent.com/662944/113061425-dcadc700-9166-11eb-993b-a94f8845b87d.png)

This appears to be once for each file (or hopefully once for each package) minus the component in the lazily loaded engine, which I suspect will have another copy in it's own vendor.js.

I would expect that w/in the app's vendor.js there would only be one copy of the autocomplete.js library.

**Comment by ef4** [comment]
Do all your packages resolve to the same physical on-disk copy of autocomplete.js?

You can check each of your packages like:

```
cd your-package
node -e "console.log(require.resolve('autocomplete.js/package.json'))")
```

ember-auto-import will follow whatever NPM does. If there is one copy, they will share one copy. If there are four distinct copies, auto-import will have four copies, and in that case you should fix that by forcing yarn or NPM to hoist & deduplicate.

If you have only one real copy of autocomplete.js, then this is indeed a bug and we'll need to dig in. Try running `DEBUG="ember-auto-import:*" ember b` and sharing the results.

**Comment by tomwayson** [comment]
Thank you for your quick reply.

My apologies - I tried to catch you before replying. The "signature" I was using turned out to not be unique - and it actually appears in the autocomplete.js source code 3 times.
