### ISSUE TITLE
Unable to use CDN url in publicAssetURL

### ISSUE THREAD

**Issue by josemarluedke** [ef4/ember-auto-import#381]
In order to use a CDN for the webpack chunks, we tried setting `publicAssetURL` to the CDN URL, but somewhere in the way that URL becomes something like this:  `http://localhost:4200/XXXXX.cloudfront.net/platform-web/assets/chunk.1.2887d153570b32f3dd1d.js`

The value of `publicAssetURL` was a full URL `https://XXXXX.cloudfront.net/platform-web/assets/`.

**Comment by urbany** [comment]
Any hack to fix this in the meanwhile?

**Comment by ef4** [comment]
I'm not able to reproduce this on ember-auto-import 2.0.1. Please open a new issue if this still occurs and you can reproduce it.
