### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Gaurav0** [ef4/ember-auto-import#40]
I would like the option to provide a whitelist and only import dependencies listed.

**Comment by Gaurav0** [comment]
Some background discussion:

https://discuss.emberjs.com/t/ember-auto-import-1-0-released/14997/7

**Comment by ef4** [comment]
I would put this in the same category as https://github.com/ef4/ember-auto-import/issues/35.

It's not really the core use case for _auto_ import. I would be happy to split out common code into a library that could be used by a separate addon that works this way.
