### ISSUE TITLE
[v2] Hundreds of Babel warnings

### ISSUE THREAD

**Issue by boris-petrov** [ef4/ember-auto-import#403]
I migrated to v2 and now when I run `ember serve` I get:

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
```

A million times. Using v1 I get it only once.

Actually this can be reproduced by just doing (because the default blueprint contains `ember-auto-import` v1):

```sh
ember new foo
cd foo
ember serve
```

And the warning will appear (once). To reproduce the million times:

```sh
ember new bar
cd bar
npm install --save-dev ember-auto-import@2 webpack lodash-es
```

Add a `foo.js` file in `app/components` with the following:

```javascript
import Component from '@ember/component';

export default class Foo extends Component {
  async foo() {
    return import('lodash-es');
  }
}
```

Run `ember serve`.

**Comment by fusion2004** [comment]
I was also seeing this in one of our ember apps that I tested upgrading to v2 on.

**Comment by jcardali** [comment]
Same behavior for me. Was hopeful that adding `loose: true` to `ember-cli-build` would fix, but no dice.

**Comment by boris-petrov** [comment]
@ef4 - thanks, with that fix the warning count is back down to 1. Any ideas why there is this one warning though?

**Comment by ef4** [comment]
@boris-petrov I'm not sure, when I did the fix it eliminate all the warnings in the test app I was looking at. But every addon brings its own babel config, so maybe one of the one you're using has this config issue.
