### ISSUE TITLE
[v2] Import of an unavailable module returns an empty object

### ISSUE THREAD

**Issue by boris-petrov** [ef4/ember-auto-import#407]
One of my transitive dependencies uses [sax](https://github.com/isaacs/sax-js) which internally does a `require('stream').Stream` [call](https://github.com/isaacs/sax-js/blob/v1.2.4/lib/sax.js#L163). Note that `sax-js` doesn't include a `stream` library in its dependencies. In `ember-auto-import` v2 this is turned into:

```javascript
var Stream;
try {
    Stream = __webpack_require__(/*! stream */
    "?9b8d").Stream;
} catch (ex) {
    Stream = function() {}
    ;
}
```

The `__webpack_require__` function returns an empty object and because of that `Stream` is set to `undefined` which blows up later in the code.

This was not the case in `ember-auto-import` v1 (I believe there the require failed and hence the catch block was executed).

What's the reason for this behavioral change and what can I do about it?

**Comment by ef4** [comment]
I think it normally should fail, are you sure you don't have any webpack config polyfilling `stream` with an empty object?

**Comment by boris-petrov** [comment]
Thanks for the support!

I now checked. With `ember-auto-import` v1 this code is generated:

```javascript
var Stream;
try {
  Stream = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'stream'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())).Stream;
} catch (ex) {
  Stream = function () {};
}
```

So as you see, in this case the `catch` block will be executed and the rest of the code works correctly.

I'm sure I don't have `webpack` config concerning anything related to `stream`, yes.

Does that help?

**Comment by ef4** [comment]
I confirmed that out-of-the-box, a library that tries to `require('stream')` causes a build failure under both ember-auto-import 1.x and 2.x, as intended.

If your app has no custom autoImport config, then I think some addon has one that is setting up a polyfill for stream that is messing you up. Search through your addons for `autoImport`.

To setup a stream polyfill or empty stream object under 2.x (which uses webpack 5), see  https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a
