### ISSUE TITLE
Defining webpack externals breaks addon v2

### ISSUE THREAD

**Issue by josemarluedke** [ef4/ember-auto-import#412]
First, Thank you for working on the v2 as a shim to Embroider and making it possible to have the addon v2 format available without Embroider.

I have a working addon with published addon v2 format [Glimmer Apollo](https://github.com/josemarluedke/glimmer-apollo).
The addon seems to work fine both in Ember CLI Classic, as well as in Embroider (We have testes passing in CI).

I found an issue where it only happens when the host app defines a Webpack config `autoImport` for the externals option. When externals are set, ember-auto-import tries to resolve Ember dependencies, like `ember/application`. 

I have a reproduction of this issue as a PR in my project: https://github.com/josemarluedke/glimmer-apollo/pull/18. 

Let me know if you have any questions about the setup or need any clarifications.

**Comment by ef4** [comment]
That's awesome that you have ported Glimmer Apollo. Glad it is mostly working.

It looks like we no longer merge user-provided externals correctly in with the ones we provide.

**Comment by vstefanovic97** [comment]
@josemarluedke did you find a workaround for this? I am running into the same problem.
I'm trying to include `ember-resources` which is a v2 addon, but the build is failing while I have `jQuery` defined as a Webpack external.

**Comment by vstefanovic97** [comment]
@ef4 I made a PR with a potential fix for this https://github.com/ef4/ember-auto-import/pull/487
Now the externals use an array of [combined syntaxes](https://webpack.js.org/configuration/externals/#combining-syntaxes) so that we can merge the configuration correctly.

**Comment by ef4** [comment]
Fixed in #487.
