### ISSUE TITLE
Support Custom Script Attributes when inserting

### ISSUE THREAD

**Issue by Eric162** [ef4/ember-auto-import#418]
https://github.com/ef4/ember-auto-import/blob/1a581312739e1be8c0fc2426586df14a1a77d864/packages/ember-auto-import/ts/inserter.ts#L111

I have a use-case that needs to add a placeholder for SSR vs non-SSR `defer` attributes (replacement of the placeholder is handled by another library). 

Because our `defer` placeholder is being conditionally replaced in a build step _after_ ember-auto-import has run, the `publicAssetURL` [from the config](https://github.com/ef4/ember-auto-import#customizing-build-behavior) does not help us here.

I'm requesting that an official API be added for either customizing the attributes added to the script tags, or for replacing the default insertion wrapping string/function.

**Comment by rwjblue** [comment]
Ya, we need to allow custom attributes (like defer) for the scripts that we are adding.

**Comment by ef4** [comment]
One idea for this api: create a new option named like `customScriptElement`. It contains the name of a custom element. We will look for that custom element in your HTML and use it as the template for the script tags we will insert. This controls both where they appear and what attributes they will have:

```js
customScriptElement: "auto-import-scripts"
```

```html
<auto-import-scripts defer/>
```
