### ISSUE TITLE
Outputs file when not used in app

### ISSUE THREAD

**Issue by mydea** [ef4/ember-auto-import#422]
While trying to debug https://github.com/ef4/ember-auto-import/issues/420, I noticed that I always get a bundle (e.g. /assets/chunk.143.f3770ae5a87436ec20ec.js), even if auto-import is not used in my app.

Since ember-auto-import comes with the default blueprint and is needed for ember-qunit, it is not that uncommon to have it installed "as a side effect" and not because I actually use it in my app. In such cases, it seems unexpected to me to end up with an "unneeded" file:

```js
var __ember_auto_import__;
(() => {
    var e = {
            320: (e, r, t) => {
                var o "undefined" != typeof document && (t.p = (o = document.querySelectorAll("script"))[o.length - 1].src.replace(/\/[^/]*$/, "/")), e.exports = function() {
                    _eai_d
                    var e = _eai_r
                    window.emberAutoImportDynamic = function(r) {
                        return 1 === arguments.length ? e("_eai_dyn_" + r) : e("_eai_dynt_" + r)(Array.prototype.slice.call(arguments, 1))
                    }, window.emberAutoImportSync = function(r) {
                        return e("_eai_sync_" + r)(Array.prototype.slice.call(arguments, 1))
                    }
                }()
            },
            608: function(e, r) {
                window._eai_r = require, window._eai_d = define
            }
        },
        r = {}

    function t(o) {
        var n = r[o]
        if (void 0 !== n) return n.exports
        var _ = r[o] = {
            exports: {}
        }
        return e[o].call(_.exports, _, _.exports, t), _.exports
    }
    t.p = "", t(608)
    var o = t(320)
    __ember_auto_import__ = o
})()
```

Which adds a full HTTP request to my app.

I would expect to not have a file in production if I do not use ember-auto-import in my app code.

This can be seen on a "plain" app created with ember-cli 3.27, e.g. see: https://github.com/mydea/ember-issue-reproductions

Semi-related, I also noticed that it always outputs a chunk file for qunit, even when running `ember b --prod` or specifically setting `tests: false` in `ember-cli-build.js`. This has not necessarily an impact as the file is not referenced anywhere, but it is still deployed etc. along with the other files and also seems like it should not be generated when tests are not run.

Not sure if these issues are known/to be expected or not, but it did appear unexpected to me at least ;)

**Comment by ef4** [comment]
I think this was addressed along with the changes in #424.
