### ISSUE TITLE
Could not find module `reserved-subdomains`

### ISSUE THREAD

**Issue by sdhull** [ef4/ember-auto-import#423]
As always: many thanks for your work on this project!

```
loader.js:247 Uncaught (in promise) Error: Could not find module `reserved-subdomains` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at eval (reserved-subdomains.js:1)
    at Object.../externals/reserved-subdomains.js (chunk.8da5fe87276f1e261e89.js:2511)
    at __webpack_require__ (chunk.d08d881df3d420b90edf.js:31)
    at eval (create-app.js:17)
    at Module../components/create-app.js (chunk.8da5fe87276f1e261e89.js:963)
    at __webpack_require__ (chunk.d08d881df3d420b90edf.js:31)
    at Module.eval [as callback] (sparkmint.js:277)
```

I've just upgraded my app from Ember 3.15.0 to 3.27.5, and auto-import from 1.5.3 to 1.11.3. This was working fine previously but no longer. Guidance would be much appreciated 🙏

**Comment by ef4** [comment]
Is this app using embroider?

Try running `npx are-my-node-modules-messed-up`.

Does your app use reserved-subdomains directly or is this through another library or addon?

**Comment by sdhull** [comment]
It makes me so happy to see your reply on my issue @ef4 😭 I've been out of the ember world for over a year now and just picking this side project back up now.
1. Yes, it's using embroider. And it was previously using 0.13.0 (altho I also see 0.4.3 in the old yarn lock file 🧐), which has been upgraded to 0.33.0.
2. The app uses reserved-subdomains directly

```
ツ npx are-my-node-modules-messed-up
npx: installed 23 in 3.428s
babel-loader asked for webpack 2 || 3 || 4 but got 5.44.0
  - in peerDependencies at node_modules/@embroider/babel-loader-7/node_modules/babel-loader
Your node_modules are messed up.
```

**Comment by sdhull** [comment]
I notice this in my yarn.lock file: 🧐 
```
babel-loader@7:
  version "7.1.5"
  resolved "https://registry.yarnpkg.com/babel-loader/-/babel-loader-7.1.5.tgz#e3ee0cd7394aa557e013b02d3e492bfd07aa6d68"
  integrity sha512-iCHfbieL5d1LfOQeeVJEUyD9rTwBcP/fcEbRCfempxTDuqrKpu0AZjLAQHEQa3Yqyj9ORKe2iHfoj4rHLf7xpw==
  dependencies:
    find-cache-dir "^1.0.0"
    loader-utils "^1.0.2"
    mkdirp "^0.5.1"

babel-loader@^8.0.6, babel-loader@^8.2.2:
  version "8.2.2"
  resolved "https://registry.yarnpkg.com/babel-loader/-/babel-loader-8.2.2.tgz#9363ce84c10c9a40e6c753748e1441b60c8a0b81"
  integrity sha512-JvTd0/D889PQBtUXJ2PXaKU/pjZDMtHA9V2ecm+eNRmmBCMR09a+fmpGTNwnJtFmFl5Ei7Vy47LjBb+L0wQ99g==
  dependencies:
    find-cache-dir "^3.3.1"
    loader-utils "^1.4.0"
    make-dir "^3.1.0"
    schema-utils "^2.6.5"
```

No idea if this is related, but it appears that `@embroider/webpack@^0.41.0` requires both `@embroider/babel-loader-7` (which requires babel-loader 7) and `babel-loader "^8.2.2"` 🤔

**Comment by sdhull** [comment]
After googling `are-my-node-modules-messed-up`, tried `rm -rf node_modules` and re-installed with `yarn` and `npx are-my-node-modules-messed-up` still complains. After getting frustrated (and since I'm upgrading dependencies anyway), I just tried `yarn upgrade` and a bunch of stuff got upgraded. `are-my-node-modules-messed-up` still complains but my app works again so 🤷

**Comment by ef4** [comment]
Embroider has been moving really fast with bug fixes lately, that could explain it. Glad it's now working.

In general, once you're using Embroider ember-auto-import doesn't do very much, so if you have more trouble in this area file issues on Embroider.
