### ISSUE TITLE
Remove code splitting and chunks on v2 with webpack 5

### ISSUE THREAD

**Issue by chadian** [ef4/ember-auto-import#426]
Hello, I am trying to limit the final output to just the app and vendor js files like the default result from a new ember app with `ember-auto-import@1.11.3` and `webpack@4.46.0` via `ember build --environment=production`

```
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/chunky-a1897aa58bcb0217b9ddedabc84a9797.js: 4.63 KB (1.37 KB gzipped)
 - dist/assets/chunky-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/vendor-c3db4aa703d764f4379c3f6c652f031b.js: 743.78 KB (195.92 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

When upgrading to `ember-auto-import@2.0.2` and `webpack@5.47.1` the production build outputs:
```
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/chunk.143.94c9da136ea875c18b39.js: 739 B (397 B gzipped)
 - dist/assets/chunk.178.d1d1af871429a6ccb44f.js: 739 B (401 B gzipped)
 - dist/assets/chunky-a1897aa58bcb0217b9ddedabc84a9797.js: 4.63 KB (1.37 KB gzipped)
 - dist/assets/chunky-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/vendor-0a6419a4459da838d8081ef4c43918dc.js: 742.45 KB (195.47 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

I looked at using the [`LimitChunkCountPlugin`](https://webpack.js.org/plugins/limit-chunk-count-plugin/) within `ember-cli-build` but it did not have any effect:
```
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    autoImport: {
      webpack: {
        plugins: [
          new webpack.optimize.LimitChunkCountPlugin({
            maxChunks: 1,
          }),
        ]
      }
    }
  });
```

I've created a sample repo that hopefully helps reproduce this with the minimum necessary changes from a new ember app:
https://github.com/chadian/ember-auto-import-chunk-test

Is there a way with `ember-auto-import` and/or `webpack` that the final build can be limited to just the vendor and app js files? Any guidance or tips on this is much appreciated, thanks!

**Comment by ef4** [comment]
It's possible to limit webpack to a single JS chunk. Mostly I think by adjusting [SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/). But that single JS chunk will always still appear as a separate file from app.js and vendor.js, which have nothing to do with webpack.

You could postprocess your build to append the JS chunk to vendor.js, but that will break sourcemaps. That is one of the reasons we stopped doing it automatically.

Why do you want to do this?

**Comment by chadian** [comment]
Thanks for responding @ef4. The current deploy process is not built to handle additional chunk files (mentioned in the [upgrade guide](https://github.com/ef4/ember-auto-import/blob/master/docs/upgrade-guide-2.0.md#inject-entry-chunks-directly-in-indexhtml)). It was simpler to pull in the two expected js files. We don't use the index.html from the build either and our ember app does not auto-boot. I haven't looked into it yet but maybe parsing a manifest of the build output with `ember-cli-deploy-manifest` or similar would include the chunk files and give us enough information to setup the necessary script tags.

**Comment by ef4** [comment]
Assuming you don't use index.html because you're embedding the app into something else, you have a couple options.

You could parse the built index.html to discover what scripts and styles are needed, and insert them manually into your other page.

Or you could rewrite your `app/index.html` so it only represents a piece of the page (no `<head> or `<body> for example) and take the built index.html snippet and embed it directly into your other page, so you don't need to worry about parsing it.

Regardless of how you handle index.html, you still need to deploy every chunk file that appears in `dist/assets`, because some might be lazy loaded by others even if they don't appear in the html.

**Comment by chadian** [comment]
Those are good options, thanks @ef4. Looks like it's better to invest in supporting the chunked builds than trying to get things into `vendor.js` in an awkward way.
