### ISSUE TITLE
Auto reload issue after upgrade to 2.0.2

### ISSUE THREAD

**Issue by trhamann** [ef4/ember-auto-import#429]
I have upgraded from version 1.6.0 to version 2.0.2.  No errors are occurring however the auto reload process is happening more frequently than before.  Opening / closing and searching for files in the text editor and modifying CSS files all trigger the auto reload.  We do not have any custom "autoImport" config in the app.

Is this a bug or am I missing a configuration change in the upgrade from version 1 to version 2?

I am running:

- ember-auto-import 2.0.2
- ember-source 3.21.1
- webpack 5

**Comment by ef4** [comment]
Interesting. Is your ember-cli printing which files it thinks changed?

**Comment by ef4** [comment]
And what editor are you using? Some of them create temp files that have been known to cause issues in the past.

**Comment by trhamann** [comment]
We are using Visual Studio Code and it prints out the file that was opened. We are able to get it to happen using touch in a Linux terminal as well.

**Comment by ef4** [comment]
This doesn't sound like an ember-auto-import specific problem to me.  The only time we do any file watching is if you use the `watchDependencies` option, otherwise that's all left up to ember-cli.

**Comment by trhamann** [comment]
Ok, thank you for your time.

**Comment by nag5000** [comment]
The same bug: #469
