### ISSUE TITLE
Can't disable sourcemaps with forbidEval set

### ISSUE THREAD

**Issue by apellerano-pw** [ef4/ember-auto-import#444]
If `forbidEval` is set, it forces the webpack devtool value to be `'source-map'`. It does this after applying the user's custom webpack config, so the user doesn't have a way to specify something like

```js
forbidEval: true,
webpack: {
  devtool: false,
}
```

Is there a technical reason for this? If not, is ember-auto-import open to a PR changing the behavior here?

Also we are [people with unnecessarily-specific deployment code](https://github.com/ef4/ember-auto-import/blob/0fba64e4713ed93812822440ac8cd99679e2700b/docs/upgrade-guide-2.0.md#inject-entry-chunks-directly-in-indexhtml) and adopting ember-auto-import 2.0's dynamic chunk scripts will be a project for us, so we are stuck on 1.x for now. 😞 

Is 1.x still accepting patches?

**Comment by ef4** [comment]
Yes, we can change this to be more extensible. We should probably just change the order so the user's custom webpack config takes precedence.

And yes, a PR targeting the 1.x branch would be OK.

**Comment by apellerano-pw** [comment]
Sorry for the delay, priorities shifted.

I've opened a PR for the fix in 1.x. I think the issue also exists in 2.x, but I have no projects using ember-auto-import 2.x to validate the change with.

https://github.com/ef4/ember-auto-import/blob/fe3d22a56e56422ca57467c8c3515901ba3accd7/packages/ember-auto-import/ts/webpack.ts#L208-L214
