### ISSUE TITLE
Addon-test-support importing from devDeps in addons is failing in some cases

### ISSUE THREAD

**Issue by Eric162** [ef4/ember-auto-import#456]
Not sure if this is the root cause, but I traced the error down to this check:
https://github.com/ef4/ember-auto-import/blob/684d97a147fc8d5446c4aa909c129bce438b3d23/packages/ember-auto-import/ts/package.ts#L299

What I am seeing in our addon is that we have imported `faker` in a file of our addon-test-support folder, say `my-addon/addon-test-support/some-folder/imported-here.js`.

When we get to this code, it needs to respect that items in addon-test-support may be using devDeps, as far as I understand the code I saw, which is that things from `tests` and `addon-test-support` would be in the `tests` bundle based on this code:
https://github.com/ef4/ember-auto-import/blob/684d97a147fc8d5446c4aa909c129bce438b3d23/packages/ember-auto-import/ts/bundle-config.ts#L71-L87

I wasn't able to find any branching logic for where the bundles were being made in my first pass, so it seems that getting to this check is intentional. If that is not the case, then maybe there is some kind of configuration I have missed.

My naive local solution was to do the following to that line:
using the same value of `testsPattern` from:
https://github.com/ef4/ember-auto-import/blob/684d97a147fc8d5446c4aa909c129bce438b3d23/packages/ember-auto-import/ts/bundle-config.ts#L7
I edited the line to:
```js
if (this.isAddon && !testsPattern.test(fromPath) && !this.hasNonDevDependency(name)) {
```

And was able to get my build passing with ember-auto-import 2.2.0

**Comment by rwjblue** [comment]
Chatted with @Eric162, the thing originally reported _shouldn't_ work. In @Eric162's case, he needed to make the dependency also a peerDependency (which ember-auto-import would resolve correctly).

Closing for now...
