### ISSUE TITLE
Relationship between app and add ons using different versions of ember-auto-import

### ISSUE THREAD

**Issue by ghost** [ef4/ember-auto-import#459]
I have I think four add ons I use in my Ember app which all require `ember-auto-import` under the hood. All of them are the latest `1.x` version. If I anted to update my apps version of `ember-auto-import` to `2.x`, does that imply I need to have my add ons updated to support `2.x` or is it backwards compatible?

**Comment by justinzelinsky** [comment]
> Right. 👍
> 
> > I need it to be assets/, not /assets/.
> 
> In general it's not safe to refer to any assets via relative paths like that. The problem is that if somebody deep links into a nested child route, the relative paths aren't correct anymore.

We're using a hash for our routing -- I don't think we're going to run into any deep linking issues given that. Does that sound right?
