### ISSUE TITLE
Module not found: Error: Can't resolve (built-in module like 'fs' or 'electron')

### ISSUE THREAD

**Issue by jacobq** [ef4/ember-auto-import#48]
See sample app here: https://github.com/jacobq/junk-app (HEAD commit breaks build)
Not sure what causes this, but some modules like [`electron-settings`](https://github.com/nathanbuchar/electron-settings) seem to have problems with `ember-auto-import`.

**Comment by ef4** [comment]
Thanks for sharing a reproduction, that made it easy to test the solution.

Those modules aren't available in web browsers, so the error messages are correct. But thankfully webpack already also knows about electron as a target, so you can just say:

```js
let app = new EmberApp(defaults, {
  autoImport: {
    webpack: {
      target: 'electron-renderer',
    }
  }
});
```
