### ISSUE TITLE
Feature request: Support WASM imports

### ISSUE THREAD

**Issue by luketheobscure** [ef4/ember-auto-import#49]
Since this addon uses webpack under the hood, it should be trivial to import wasm modules, such as those output by [wasm-pack](https://github.com/rustwasm/wasm-pack).

Right now, this almost "Just Works™". 

Declaring `import { Foo } from 'some-wasm-module/wasm-wrapper.js'` gets you 90% of the way there as long as the wasm wrapper imports the wasm with the syntax `const wasm = import('./path_to_wasm');` (and not `import wasm from './path_to_wasm'`).

There's only two issues blocking this that I know of:

1. Webpack puts together a file called `0.{entry point path}.js` with some of the chunking and wrapper code. This will need to be output by ember-auto-import (and made available at the URL webpack tries to download it at).

2. It looks like webpack assigns a guid filename to the actual wasm file (in the form of `{guid}.module.wasm`. This file will also need to be output by ember-auto-import.

I don't know webpack very well, but I'll keep digging into this issue and see if I can get it working. I'm more than happy to provide test cases and manual testing if anyone wants to take up the mantle on this.

**Comment by ef4** [comment]
This sounds like it might just fall out automatically from implementing dynamic `import()`, which I want to do anyway.

**Comment by luketheobscure** [comment]
Just tried out the new dynamic `import()`, and it works! The wasm chunk is even included in the assets when you build the project. 🎉

**Comment by ef4** [comment]
Haha, that is excellent news! Thanks.
