### ISSUE TITLE
Is it mandatory to have `unsafe-eval` in the CSP?

### ISSUE THREAD

**Issue by ghost** [ef4/ember-auto-import#50]
Hi, just looking at moving from ember-browserify to ember-auto-import, and after running `ember install ember-auto-import` and booting my app I got a CSP error:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'"
```

Just wondering if it's intentional that `unsafe-eval` is required to be in the CSP? And if so, this could be worth documenting.

**Comment by ef4** [comment]
This is apparently a much-discussed issue in webpack: https://github.com/webpack/webpack/issues/5627

There are a few different suggestions in there for ways to change the config to not need eval. You could try them by [adding to the webpack config](https://github.com/ef4/ember-auto-import#customizing-build-behavior) that ember-auto-import is using.

**Comment by ef4** [comment]
If you find a good solution for this, please share. It would be good to make it standard for everyone.

**Comment by musaffa** [comment]
A simple workaround is to change webpack's [devtool](https://webpack.js.org/configuration/devtool/) config:
```Javascript
autoImport: {
  webpack: {
     devtool: 'source-map'
  }
}
```
`devtool: eval` is the fastest config for the source map generation but `unsafe-eval` in CSP is indispensable.

**Comment by Alonski** [comment]
@musaffa I have set to `devtool: 'inline-source-map'`
Works for me.
Any reason to choose one over the other?

**Comment by musaffa** [comment]
If you want source map in a production site then `devtool: 'source-map'` is one of the recommended ways. It emits source-map as a separate file. `inline-source-map` is neither meant for development nor production as per devtool's [document](https://webpack.js.org/configuration/devtool/#special-cases). But you won't see any difference because ember's production build strips source maps by default. The difference will only be apparent once you enable source maps in production builds.

**Comment by IgorKvasn** [comment]
@musaffa not sure if it is just my bad setup, but when I try `devtool: source-map`, my production build does not work:
```
Build failed.
Build Error (UglifyWriter)

Unexpected token: punc (:)
```

error details from log file:
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Unexpected token: punc (:)
    at objectToError (/home/xxx/web-ember/node_modules/workerpool/lib/WorkerHandler.js:63:14)
    at ChildProcess.<anonymous> (/home/xxx/web-ember/node_modules/workerpool/lib/WorkerHandler.js:146:32)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at handleMessage (internal/child_process.js:753:14)
    at Pipe.channel.onread (internal/child_process.js:472:11)
  - codeFrame: Unexpected token: punc (:)
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `UglifyWriter` plugin
```

when I use `devtool: inline-source-map` I am at least build ember-cli at all...

**Comment by Alonski** [comment]
Awesome work @ef4 Thanks a lot!
