### ISSUE TITLE
Dynamically importing module from a pubilc URL

### ISSUE THREAD

**Issue by Narasimhan94** [ef4/ember-auto-import#508]
Hi,

I am using "ember-auto-import": "^1.5.2" and I am trying to import a module dynamically using the below command :
`import('https://..../index.esm.js').then((module) =>  console.log(module));` 

But I am facing this error 
Error: Could not find module `_eai_dyn_https://.../index.esm.js` 

Can we use ember-auto-import to import modules directly from a public CDN which is a non-npm package?

**Comment by ef4** [comment]
Hi, I think this bug was fixed 1.10.0 circa December 2020. Please upgrade to that point and give it a try and reopen if it reoccurs.
