### ISSUE TITLE
Webpack resolve alias does not work

### ISSUE THREAD

**Issue by josemarluedke** [ef4/ember-auto-import#51]
Webpack has a feature where you can specify an alias to resolve a different package/file. 

https://webpack.js.org/configuration/resolve/#resolve-alias

It seems that I can't use that with this project, at least it is not working in this example: https://github.com/josemarluedke/auto-import-alias

**Comment by ef4** [comment]
Thanks for reporting, please try 1.1.0 and use:

```
let app = new EmberApp(defaults, {
  autoImport: {
    alias: {
      'plotly.js': 'plotly.js-basic-dist'
    }
  }
});
```

(This is a top-level option because we deal with discovering dependencies before we hand off to webpack.)
