### ISSUE TITLE
Add ability to pass options to `MiniCssExtractPlugin`

### ISSUE THREAD

**Issue by boris-petrov** [ef4/ember-auto-import#514]
In `ember-cli-build.js` in `autoImport` I have:

```js
styleLoaderOptions: {
  attributes: {
    nonce: 'style-loader',
  },
  insert: function (element) {
    document.getElementsByTagName('head')[0].prepend(element);
  },
},
```

Which works great on `ember-auto-import` 2.4.1 in development but in production this is not executed and hence all styles are inserted as links at the end of `head` (which is the default behavior of `style-loader` - i.e. the `insert` option is not used at all). The same happens in 2.4.0 (it also had another [issue](https://github.com/ef4/ember-auto-import/issues/493)). In 2.3.0 that is not the case and there all works fine.

cc @ef4

**Comment by ef4** [comment]
style-loader is not recommended for production, so our default setup follows the recommendation of using it in development and using MiniCssExtractPlugin in production. Maybe what you really need is more control over the MiniCssExtractPlugin options?

**Comment by boris-petrov** [comment]
@ef4 thanks for taking a look into this. I didn't know that `style-loader` is not supposed to be used in production. Not sure what the difference is with `MiniCssExtractPlugin` but oh well. So yes, I do need what you suggest - more control over the `MiniCssExtractPlugin` options.

**Comment by boris-petrov** [comment]
hm, actually, you *can* pass options right now via `miniCssExtractPluginOptions`. So all is fine. Thank you for the support!

**Comment by ef4** [comment]
If you can suggest a place where we could have documented this better for
your use case, that would be helpful.

**Comment by boris-petrov** [comment]
Well, in this case this was my mistake - I hadn't read that `style-loader` shouldn't be used in production. But perhaps all these options could be documented in the [README](https://github.com/ef4/ember-auto-import#customizing-build-behavior), that's true.
