### ISSUE TITLE
Size Limit/Web Performance

### ISSUE THREAD

**Issue by villander** [ef4/ember-auto-import#52]
I'm getting these warnings, and that's got me worried. Is there any way to fix this @ef4 ?

Version: webpack 4.14.0
Time: 3157ms
Built at: 07/09/2018 9:41:20 AM
Asset     Size  Chunks                    Chunk Names
app.js  254 KiB       0  [emitted]  [big]  main
Entrypoint main [big] = app.js
[0] ./node_modules/process/browser.js 5.29 KiB {0} [built]
[1] ./node_modules/airbrake-js/dist/client.js 81 KiB {0} [built]
[2] ./node_modules/highcharts/highcharts.js 199 KiB {0} [built]
[3] ./node_modules/awesomplete/awesomplete.js 10.7 KiB {0} [built]
[4] ./node_modules/highcharts/modules/streamgraph.js 463 bytes {0} [built]
[5] ./node_modules/highcharts/modules/drilldown.js 9.34 KiB {0} [built]
[6] ./tmp/ember_auto_import_webpack-staging_dir-9S9NtkQU.tmp/entry.js 847 bytes {0} [built]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
 app.js (254 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
 main (254 KiB)
     app.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: Filter

**Comment by ef4** [comment]
Assuming you were already using all these dependencies via another method (like `app.import` or ember-browserify), nothing has gotten worse. webpack is just more obnoxious about size-shaming people.

The size is mostly due to highcharts.js. If you're only using it in a few places, you would benefit from lazy loading it via `import()`, which is a feature I would like to implement soon in ember-auto-import.

**Comment by ef4** [comment]
Dynamic import is now available in 1.2.0.

**Comment by villander** [comment]
Thanks @ef4

**Comment by jrjohnson** [comment]
Is there any way to silence this once lazy loading is enabled? We still see the errors when lazy importing `zxcvbn`. They're just an annoyance since I've confirmed that the JS is getting loaded async, but they kind of freak me out.

**Comment by john-kurkowski** [comment]
Is there any way to quiet webpack output whether lazy loading or not?

> webpack is just more obnoxious about size-shaming people. … If you're only using it in a few places

I've got some big libs used everywhere, and I'm just going to take the hit. Webpacks warnings be damned. I just wish it were less verbose.

It'd be nice to have the full flexibility of Webpack's [`stats`](https://webpack.js.org/configuration/stats/). But maybe that's not so easy to do, because this project uses their programmatic API?

> _This option does not have any effect when using the Node.js API._

**Comment by john-kurkowski** [comment]
> Webpacks warnings be damned. I just wish it were less verbose.

Or maybe I need more Webpack education? Coming from Ember CLI, I haven't had to worry about Webpack before. Maybe a FAQ entry on Webpack console output, common remedies, and what to expect maintaining those remedies? Is dynamic import the only possible step?

**Comment by Alonski** [comment]
I would also love some info on how to gleam more info out of this.
Also a way to silence would also be nice :)
During builds of our app I am getting:
```js
Assets:
  chunk.cbe2c8cbffcb3f514b5e.js (423 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.

Entrypoints:
  app (425 KiB)
      chunk.cbe2c8cbffcb3f514b5e.js
      chunk.b9e43121ae0c4b5ce75e.js
```

**Comment by lifeart** [comment]
looks like it's possible to disable it with 
`performance: { hints: false }`  https://github.com/webpack/webpack/issues/3486

**Comment by ef4** [comment]
Yeah, I personally disagree with Webpack's choice to scold by default. Their limits are quite arbitrary, what is "too big" for some situations is perfectly fine for others. And bytes is *not* the relevant metric anyway, it's secondary to what really matters, which is metrics like time-to-first-paint and time-to-interactive.

I'm fine with changing the defaults inside `@embroider/webpack` to turn the scolding off.

**Comment by john-kurkowski** [comment]
> looks like it's possible to disable it with
> `performance: { hints: false }`

This does disable the shaming entirely. Thanks!

I don't suppose there's a way to filter it? Looks like it's all or nothing. There no, "I know lib xyz.js is big, so exclude it from hinting, but tell me about other problems." `performance`'s `assetFilter` option only sees the anonymous `chunk.0123.js` files.

**Comment by ef4** [comment]
Changing the default to `{ hints: false }` in https://github.com/ef4/ember-auto-import/pull/214
