### ISSUE TITLE
Updating to ember-auto-import@2 is now not able to find module but only in prember

### ISSUE THREAD

**Issue by mansona** [ef4/ember-auto-import#532]
Howdy folks 👋 

I'm trying to upgrade Guidemaker to finally support Ember 4.0 but I'm having a bit of trouble upgrading to ember-auto-import@2

Here is my PR that is currently failing: https://github.com/empress/guidemaker/pull/73

Essentially everything is working fine with the app in the browser but for Fastboot it just can't find something that is specified in the dependencies. I have tried a bunch of solutions to see what the problem might be but I've had no luck. 

Does anyone know any solution to this? or does anyone have any debug steps that I might be able to try?

**Comment by ef4** [comment]
That PR is missing the required webpack dependency, but it seems like you probably knew that because I could only reproduce your problem after adding it.

This doesn't appear to be a problem with fastboot. You can see the fastboot-rendered output is working fine in development. This appears to be a problem with prember.

**Comment by mansona** [comment]
> That PR is missing the required webpack dependency, but it seems like you probably knew that because I could only reproduce your problem after adding it.

eh... I didn't know that 😬 I guess I have a rogue webpack in my global node modules somewhere. I'll add that in thanks 👍 

and I guess you're right, I didn't actually consider this was specifically a prember issue 🤔

**Comment by ef4** [comment]
Please try prember 1.1.1, I think that fixes it.

**Comment by ef4** [comment]
RE the webpack dependency, see the upgrade guide here: https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md#apps-responsible-for-installing-webpack

**Comment by mansona** [comment]
yea I think I have it in the main upgrade branch. This was an off-shoot to try to isolate the thing that was breaking 👍 

Thanks a million for the quick turnaround on this one, I super appreciate it 😍
