### ISSUE TITLE
Uncaught Error: Could not find module `fast-memoize`

### ISSUE THREAD

**Issue by tomcornelis** [ef4/ember-auto-import#534]
I need to add ember-auto-import (as part of upgrading moment 2.24 to 2.29.4), but this seems to conflict with ember-intl (which already requires ember-auto-import) too and suddenly causes the following error (even though ember-intl worked fine before I've added ember-auto-import)

```
Uncaught Error: Could not find module `fast-memoize` imported from `ember-intl/-private/formatters/-format-datetime`
```

What could be the cause of this issue?

**Comment by artemgurzhii** [comment]
Having the same issue, my stack:

```
Ember: 3.28.9
Ember Data: 3.28.10
Ember Bootstrap: 5.1.1
ember-auto-import: 2.4.2
ember-intl: 5.7.2
```

**Comment by artemgurzhii** [comment]
@tomcornelis I found what is the issue, in my case `fast-memoize` is actually loaded,

I had such config:
```
autoImport: {
  forbidEval: true,
  publicAssetURL: '/assets',

  alias: {},

  exclude: [],
  insertScriptsAt: 'auto-import-scripts',
},
```

and such fingerprint

```
const fingerprint = IS_PROD
  ? {
      prepend: './',
      enabled: true,
      generateAssetMap: true,
    }
  : {};
```

changing from `publicAssetURL: '/assets',` to `publicAssetURL: './assets',` fixed the issue

**Comment by ef4** [comment]
> P.S. General recommendation...

Yes, do not fall into the trap of focussing attention only on the stack trace (which happens second) and ignoring the HTTP 404 for the script (which happens first). The first error error is the actual cause. The second error is a symptom of the first.

**Comment by artemgurzhii** [comment]
@ef4 I agree, and it would be great to document it somewhere, something like I have written above, but in a more smart/correct way

**Comment by tomcornelis** [comment]
@artemgurzhii Thanks for hinting me in the right direction.

 In my case my ember app (through the vendor and app javascripts) was integrated in another other html page, instead of the standard app/index.html. 
Therefore I was able to solve it by also including the script tags for the dist/assets/chunk*.js in this custom html page.
