### ISSUE TITLE
Auto import not working when using ember-cli-babel with custom babel config

### ISSUE THREAD

**Issue by colenso** [ef4/ember-auto-import#549]
I'm trying to conditionally disable the `compress` option for `ember-cli-babel` in my project and hence using a custom `babel.config.js` file with `useBabelConfig: true`. But this causes some imports to not work namely something like:
`import moment from 'moment-timezone';` doesn't resolve. But if I set `useBabelConfig: false` then the imports work like they should. Here's my `babel.config.js` contents:
```
const { buildEmberPlugins } = require("ember-cli-babel");

module.exports = function (api) {
  api.cache(true);

  return {
    presets: [
      [
        require.resolve("@babel/preset-env"),
        {
          targets: require("./config/targets"),
        },
      ],
    ],
    plugins: [
      // if you want external helpers
      [
        require.resolve("@babel/plugin-transform-runtime"),
        {
          version: require("@babel/plugin-transform-runtime/package").version,
          regenerator: false,
          useESModules: true,
        },
      ],
      // this is where all the ember required plugins would reside
      ...buildEmberPlugins(__dirname, { /*customOptions if you want to pass in */ }),
    ],
  };
};
```

**Comment by ef4** [comment]
`ember-cli-babel`'s `useBabelConfig` option disables *all* automatic installation of babel plugins by addons like ember-auto-import. If you want to use it, you'll need to manually figure out what babel plugins your addons would have been using and how they're configured.

I can't recommend `useBabelConfig` unless you're willing to read the source of each of your addons each time you upgrade them and something like this breaks. For ember-auto-import, the plugin you're missing gets installed [here](https://github.com/ef4/ember-auto-import/blob/57415505d055f261d2011187b8a1dca822c8452c/packages/ember-auto-import/ts/auto-import.ts#L204). 

I agree with the goal of having a real standalone babel config, but people need an easier upgrade path that will help them discover or automatically configure the same set of babel plugins they had before.  I think the more pleasant upgrade path is to wait for addons to convert to v2 format, which forbids them from installing babel plugins automatically inside your app build. 

Finally, I can't figure out what `compress` option you're referring to. As far as I can tell, there is no such option to current versions of `ember-cli-babel` or `@babel/core` or `broccoli-babel-transpiler`. I suspect whatever it is you're trying to do doesn't really require `useBabelConfig: true`.

**Comment by colenso** [comment]
I'm sorry, I meant the `compact` option not `compress`. I followed this thread https://github.com/babel/ember-cli-babel/issues/302 and got stuck at the same place as https://github.com/babel/ember-cli-babel/issues/302#issuecomment-886931850. Thanks for your explanation as what `useBabelConfig` really does internally. 
Is there any easy way to turn off the `compact` option? https://babeljs.io/docs/en/options#compact

**Comment by ef4** [comment]
Oh yeah, that isn't easy, apparently.

I think there are two ways somebody could contribute the fix to ember-cli-babel.

The smaller one is to just make generatorOpts work correctly. It's probably like a four line change, to make sure `generatorOpts` doesn't get passed to preset-env and does get passed to babel.

The bigger one is to finish `useBabelConfig: true` properly, by creating a way to capture the addon-added plugins in your standalone babel config. It's definitely possible. One way to do it would be to expose a babel plugin from `ember-cli-babel` that you put your in your babel config, and its implementation is "delegate to all the plugins added by my addons".
