### ISSUE TITLE
Error during eval. Possible bad escaping of module?

### ISSUE THREAD

**Issue by cibernox** [ef4/ember-auto-import#58]
This happens when importing `luxon` (https://moment.github.io/luxon/) on an app or addon.

Steps to reproduce:

1. Create a new app or addon
2. Add "ember-auto-import" and "luxon" as dependencies.
3. In some file that is requires immediately, like the application controller, add `import { DateTime } from "luxon"`
4. The error I get is: 
```
Uncaught SyntaxError: Unexpected token :
    at Object../node_modules/luxon/build/cjs-browser/luxon.js
```

I created a repro to help: https://github.com/cibernox/addon-with-luxon (it's an addon it can also be reproduced on an app)

Since I don't think luxon really has a syntax error in its source code, I suspect that the escaping to convert the library to a string has a bug.

**Comment by cibernox** [comment]
Same. I had this working but now it fails. I tried downgrading luxon and ember-auto-import but it keeps failing. I'm almost sure that it's failing because of an update in webpack.
(use Ember they said, you won't have to worry about webpack they said...)

After further digging I discovered that the syntax error is in the very end of the eval'ed string, in the webpack comment: 
```
exports.FixedOffsetZone = FixedOffsetZone;
exports.IANAZone = IANAZone;
exports.LocalZone = LocalZone;
exports.Settings = Settings;
sourceURL=webpack://__ember_auto_import__/./node_modules/luxon/build/cjs-browser/luxon.js?
```

Seems that the last line should be a comment but it's not.

**Comment by ef4** [comment]
I think this is a bug in broccoli-concat. Here's the very end of the module's definition before and after concat:

```
exports.Settings = Settings;\n//# sourceMappingURL=luxon.js.map\n\n\n//# sourceURL=webpack://__ember_auto_import__/./node_modules/luxon/build/cjs-browser/luxon.js?");
exports.Settings = Settings;\nsourceURL=webpack://__ember_auto_import__/./node_modules/luxon/build/cjs-browser/luxon.js?");
```

**Comment by ef4** [comment]
@cibernox's repro app stops being broken if you disable sourcemaps:

```
diff --git a/ember-cli-build.js b/ember-cli-build.js
index dc5a39e..89729fe 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -5,6 +5,9 @@ const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
 module.exports = function(defaults) {
   let app = new EmberAddon(defaults, {
     // Add options here
+    sourcemaps: {
+      enabled: false
+    }
   });

   /*
```

**Comment by cibernox** [comment]
Maybe it's the concatenation of sourcemaps?

**Comment by ef4** [comment]
I'm pretty confident this is a bug in the sourcemap-aware concatenation in either broccoli-concat or fast-sourcemap-concat. If somebody can reduce this failure to a test case there it would help.

For now, the best workaround is disabling sourcemaps in your app.

**Comment by jeanduplessis** [comment]
Was able to narrow down the dependency causing the issue to fast-sourcemap-concat 1.3.1 release.
Opened an issue there: https://github.com/ef4/fast-sourcemap-concat/issues/53

**Comment by ef4** [comment]
Dammit, I can only blame myself. 😝

**Comment by ef4** [comment]
The root cause is in source-map-url, which is a dep of fast-sourcemap-concat. I did a patch release of fast-sourcemap-concat that downgrades source-map-url, and it fixes this bug. 

Allow your version of fast-sourcemap-concat to update to 1.3.2 and this problem should go away.
