### ISSUE TITLE
Dynamic import in dependency references wrong location

### ISSUE THREAD

**Issue by alexlafroscia** [ef4/ember-auto-import#64]
I'm trying to leverage `ember-auto-import` in one of my addons ([`ember-cli-stencil`](https://github.com/alexlafroscia/ember-cli-stencil)) to solve an issue where [Stencil](https://stenciljs.com/) packages [need to be imported through ESM](https://github.com/alexlafroscia/ember-cli-stencil/issues/5).

The packages contain dynamic imports to lazy-load their component definitions. This seems to be OK, although the location of the "chunk" that it's importing is wrong.T

The file is trying to be loaded at `localhost:4200/chunk.whatever.js` (which fails)

<img width="743" alt="screen shot 2018-07-14 at 4 35 24 pm" src="https://user-images.githubusercontent.com/1645881/42729155-1aedc03c-8784-11e8-8965-d71d4ed2e21b.png">

when it actually lives at `localhost:4200/assets/chunk.whatever.js`

<img width="626" alt="screen shot 2018-07-14 at 4 35 48 pm" src="https://user-images.githubusercontent.com/1645881/42729154-1799103a-8784-11e8-8734-00f3911da0db.png">

**Comment by ef4** [comment]
Thanks, I used [your PR](https://github.com/alexlafroscia/ember-cli-stencil/pull/6) as a test case to help track this down. Fix is released as 1.2.5.

**Comment by alexlafroscia** [comment]
Awesome, thanks for following up!
