### ISSUE TITLE
Another jquery libraries issue

### ISSUE THREAD

**Issue by MrChriZ** [ef4/ember-auto-import#68]
I think this might be the same as the other jquery question here.
I'm trying to import flickity.
I've tried various combinations of 
```
import flickity from "flickity";
import "flickity";
```
However when I do
`$('.main-carousel').flickity({})`
in my component I get  Uncaught ReferenceError: flickity is not defined.

**Comment by MrChriZ** [comment]
Ah no I think I realise what I've done...I was calling it from init when the element didn't exist yet.

**Comment by ef4** [comment]
Oh yes, I think you're right and this is probably the same as #59. And I think I have a good idea what's going on, will comment there.
