### ISSUE TITLE
not working with ember-cli 3.1.3

### ISSUE THREAD

**Issue by aaronucsd** [ef4/ember-auto-import#69]
I have ember 3.x and following the two basic steps to install `lodash-es` didn't work. The import below results in `capitalize is not defined`.
Install:
ember install ember-auto-import
yarn add --dev lodash-es

Usage:
import { capitalize } from 'lodash-es';

**Comment by FutoRicky** [comment]
@aaronucsd Could you share how you fixed this? I'm having the same issue.
