### ISSUE TITLE
Cannot make ember-auto-import work at all

### ISSUE THREAD

**Issue by boris-petrov** [ef4/ember-auto-import#70]
I tried following the `Usage` step in the README but it doesn't seem to work in our project:

```
Uncaught Error: Could not find module `lodash-es` imported from `frontend/app`
```

And I've done just the couple of steps in the example. I tried also a bunch of other things but no luck. We have a big `ember-cli-build.js` file (like 230 lines of code) and I did try removing most of the things inside and still it doesn't do anything. (Part of) the debug output:

```
  ...
  ember-auto-import:analyzer     "specifier": "../config/environment",
  ember-auto-import:analyzer     "path": "frontend/tests/test-helper.js",
  ember-auto-import:analyzer     "isDynamic": false,
  ember-auto-import:analyzer     "package": "frontend"
  ember-auto-import:analyzer   },
  ember-auto-import:analyzer   {
  ember-auto-import:analyzer     "specifier": "@ember/test-helpers",
  ember-auto-import:analyzer     "path": "frontend/tests/test-helper.js",
  ember-auto-import:analyzer     "isDynamic": false,
  ember-auto-import:analyzer     "package": "frontend"
  ember-auto-import:analyzer   },
  ember-auto-import:analyzer   {
  ember-auto-import:analyzer     "specifier": "ember-qunit",
  ember-auto-import:analyzer     "path": "frontend/tests/test-helper.js",
  ember-auto-import:analyzer     "isDynamic": false,
  ember-auto-import:analyzer     "package": "frontend"
  ember-auto-import:analyzer   }
  ember-auto-import:analyzer ] +0ms
  ember-auto-import:splitter output {
  "app": {
    "static": [],
    "dynamic": []
  },
  "tests": {
    "static": [],
    "dynamic": []
  }
} +0ms
  ember-auto-import:bundler extraWebpackConfig {} +0ms
Hash: 36ab3b91265ef5407c05
Version: webpack 4.16.1
Time: 60ms
Built at: 07/19/2018 2:22:29 PM
   Asset      Size  Chunks             Chunk Names
  app.js   4.3 KiB     app  [emitted]  app
tests.js  4.31 KiB   tests  [emitted]  tests
Entrypoint app = app.js
Entrypoint tests = tests.js
[./tmp/ember_auto_import_webpack-staging_dir-bG1Hzmkb.tmp/app.js] 192 bytes {app} [built]
[./tmp/ember_auto_import_webpack-staging_dir-bG1Hzmkb.tmp/tests.js] 192 bytes {tests} [built]
```

What might I be doing wrong? Any ideas/suggestions to debug this?

P.S. Forgot to mention - Ember and Ember CLI versions 3.3.0.

**Comment by ef4** [comment]
In the part of the debug output that you trimmed out, is there any mention of lodash-es? Specifically something like:

```
  ember-auto-import:analyzer   {
  ember-auto-import:analyzer     "specifier": "lodash-es",
  ember-auto-import:analyzer     "path": "frontend/app.js",
  ember-auto-import:analyzer     "isDynamic": false,
  ember-auto-import:analyzer     "package": "frontend"
  ember-auto-import:analyzer   },
```

If yes, then double check that lodash-es appears in your devDependencies in package.json.

If no, then something is preventing the analyzer from seeing the import. Possibly some other preprocessor is getting in the way. Try building the app with `BROCCOLI_DEBUG=ember-auto-import:*`. This will produce a `DEBUG` directory. Take a look at the stuff under `DEBUG/ember-auto-import/preprocessor`. Somewhere in there should be your file that contains the `import` statements. Is it there? Has it been preprocessed in some way?

**Comment by boris-petrov** [comment]
Hi, thanks for the quick response!

1) `lodash` is not mentioned at all in the debug output.
2) I put this import in `app.coffee` (yes, we use CoffeeScript, maybe that's the problem?). `app.coffee` can be found in `frontend/DEBUG/ember-auto-import/preprocessor/input-0/frontend/app.coffee` and is unchanged from the original version.

Does that help?

**Comment by boris-petrov** [comment]
It does fix the issue. I've opened a PR. Thanks for the support!
