### ISSUE TITLE
`mainFields` not configurable through `webpack.resolve.mainFields`

### ISSUE THREAD

**Issue by jasonmit** [ef4/ember-auto-import#74]
The resolver that ember-auto-importer uses to build up stats of all the entrypoints does not take into account user provided options passed via `webpack.{mainFields,extensions}`.

https://github.com/ef4/ember-auto-import/blob/master/ts/splitter.ts#L17-L18

This is causing `graphql-js` to always resolve to `main` over `module` when in my case I need to flip the priority.  Are you open to this being configurable via the webpack options?

Related: https://github.com/bgentry/ember-apollo-client/issues/145

**Comment by ef4** [comment]
I'm OK with making this configurable as a fallback for working around problems. but in general it's not a good idea to make globally-impactful changes like reordering `mainFields` from within an addon. It can break any other thing that another addon or the app is importing.

Basically, webpack config doesn't automatically compose out of pieces very well. I want to keep customization to a minimum -- particularly in addons.

I think there is a better workaround for this. Try:

```
// In your addon's index.js file
module.exports = {
  name: 'ember-apollo-client',
  options: {
    autoImport:{
      alias: {
        "graphql-js": "graphql-js/index"
      }
    }
  }
}
```

`mainFields` only matters when trying to find the default entrypoint. You can pick a more specific entrypoint yourself.

**Comment by jasonmit** [comment]
Appreciate the quick response. It turned out this is a known issue with graphql-js and was able to resolve it differently:

```
module.exports = {
  name: 'ember-apollo-client',

  options: {
    autoImport: {
      webpack: {
        module: {
          rules: [
            /* see: https://github.com/graphql/graphql-js/issues/1272#issuecomment-393903706 */
            {
              test: /\.mjs$/,
              include: /node_modules/,
              type: 'javascript/auto',
            },
          ],
        }
      },
    },
  },
};
```

Thanks again for this great addon.
