### ISSUE TITLE
use scoped npm package

### ISSUE THREAD

**Issue by ngouy** [ef4/ember-auto-import#77]
I didn't find a way to use scoped packages. Nor with trying, nor in the doc.

So just for the record, how do you use a scoped npm package ?

>\> ember -v
< ember-cli: 2.11.1
< node: 6.11.0
```js
// whatever.js
import { process } from '@ngouy/easy-template';
```

=>
Can't resolve '@ngouy/easy-template' in '/Users/nathangouy/travail/due/www-dashboard'

Once I figured it out, I can add one or too lines into de readme to help future users

**Comment by ef4** [comment]
You don't need to do anything special for scoped packages, that should already work. I just [added test coverage to confirm](https://github.com/ef4/ember-auto-import/blob/f0fd0fdee3401bec051068139796be4eb0d779ff/test-apps/sample-direct/app/components/hello-world.js#L6).

Does `@ngouy/easy-template` appear in your project's dependencies in package.json? Does `@ngouy/easy-template` have a package.json of its own? Is it an Ember addon (it should not be if you're using ember-auto-import to pull it in)?

Try to run:

```
node -e "console.log(require.resolve('@ngouy/easy-template'))" 
```

in your project directory and see if it prints the real location of your library.
