### ISSUE TITLE
regression on 1.2.7

### ISSUE THREAD

**Issue by miguelcobain** [ef4/ember-auto-import#91]
My project was building fine until the last 1.2.7 update.

Now I get the following error, *only when building in production*:

```
Build failed.
Build Error (Bundler)

ENOENT: no such file or directory, open '/Users/miguel/workspace/my-new-addon/tmp/bundler-input_base_path-HP6s2Lju.tmp/assets/test-support.js'


Stack Trace and Error Report: /var/folders/n5/53gw98ns48q5zj5l141z2n540000gn/T/error.dump.543eaf4f8133acc5f3864fd42798c69f.log
```

Using version 1.2.6 works fine.

**Comment by ef4** [comment]
Ah. My bad. None of the tests are covering this case.

**Comment by ef4** [comment]
Released in 1.2.8.

**Comment by miguelcobain** [comment]
Thanks for such a quick fix!

**Comment by boris-petrov** [comment]
@ef4 - the same issue reappeared in 1.2.9. :)

**Comment by ef4** [comment]
@boris-petrov You're right, this got reintroduced.
