### ISSUE TITLE
what happens when 2 addons auto-import the same library or function?

### ISSUE THREAD

**Issue by tomwayson** [ef4/ember-auto-import#96]
Let's say 2 addons use ember-auto-import to import a library like moment or highcharts and then an app uses both of those addons. Would the library be included twice in the app?

What if those 2 addons imported the same function from a library (i.e. with the intention of tree-shaking it out), would that function be included twice in the app?

**Comment by ef4** [comment]
It all deduplicates correctly, as long as they're using the same version of the library.  If they aren't, we error, as there's no way to satisfy both.

**Comment by tomwayson** [comment]
Thanks for your quick response.

Wow, that's impressive!

Here's another curve ⚾️ , what if one of those addons didn't use ember-auto-imports, but instead used `app.import()` to load the library?

**Comment by ef4** [comment]
That would do double inclusion. And if the thing that is `app.import`ed the old way `define`s the same name, the last one to load will win (at the moment that is probably the one from auto import).
