### ISSUE TITLE
Exclude in FastBoot

### ISSUE THREAD

**Issue by mhluska** [ef4/ember-auto-import#98]
Some libraries throw an error when imported in the FastBoot / node environment, e.g. https://github.com/corejavascript/typeahead.js/issues/92. Is it possible to exclude them only when importing in FastBoot but not in the browser?

I'd prefer not to have to lazy load the library because then I have to pull in a bunch of babel dependencies.

**Comment by rwwagner90** [comment]
@mhluska @ef4 should we add a note about how to use dynamic imports for fastboot guards in the README? I think it could also be helpful to have a config option to use `fastboot-transform` to make sure certain libs using browser API are not attempting to run.

**Comment by rwwagner90** [comment]
@mhluska did you end up using dynamic imports for this?

**Comment by mhluska** [comment]
@rwwagner90 yes, I did something like this in my component:

```js
  init() {
    this.get('initBloodhound').perform();
    this._super(...arguments);
  },

  initBloodhound: task(function * () {
    if (this.get('fastboot.isFastBoot')) return;

    const store = this.get('store');

    // HACK: We import this dynamically so that it does not throw an error in FastBoot.
    // See https://github.com/corejavascript/typeahead.js/issues/92
    // See https://github.com/ef4/ember-auto-import/issues/98
    const module = yield import('corejs-typeahead');
    const Bloodhound = module.default;
    const bloodhound = new Bloodhound({ ... });

    this.set('bloodhound', bloodhound);
    return bloodhound;
  }),
```
